// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DataDiskInitParameters struct {

	// The id of auto snapshot policy for data disk.
	AutoSnapshotPolicyID *string `json:"autoSnapshotPolicyId,omitempty" tf:"auto_snapshot_policy_id,omitempty"`

	// Category of data disk. The parameter value options are ephemeral_ssd, cloud_efficiency, cloud_ssd and cloud.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Whether to delete data disks attached on ecs when release ecs instance. Optional value: true or false, default to true.
	DeleteWithInstance *bool `json:"deleteWithInstance,omitempty" tf:"delete_with_instance,omitempty"`

	// The description of data disk N. Valid values of N: 1 to 16. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The mount point of data disk N. Valid values of N: 1 to 16. If this parameter is not specified, the system automatically allocates a mount point to created ECS instances. The name of the mount point ranges from /dev/xvdb to /dev/xvdz in alphabetical order.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Specifies whether data disk N is to be encrypted. Valid values of N: 1 to 16. Valid values: true: encrypted, false: not encrypted. Default value: false.
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// The CMK ID for data disk N. Valid values of N: 1 to 16.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The name of data disk N. Valid values of N: 1 to 16. It must be 2 to 128 characters in length. It must start with a letter and cannot start with http:// or https://. It can contain letters, digits, colons (:), underscores (_), and hyphens (-). Default value: null.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The performance level of the ESSD used as data disk.
	PerformanceLevel *string `json:"performanceLevel,omitempty" tf:"performance_level,omitempty"`

	// Size of data disk, in GB. The value ranges [5,2000] for a cloud disk, [5,1024] for an ephemeral disk, [5,800] for an ephemeral_ssd disk, [20,32768] for cloud_efficiency, cloud_ssd, cloud_essd disk.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Snapshot used for creating the data disk. If this parameter is specified, the size parameter is neglected, and the size of the created disk is the size of the snapshot.
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type DataDiskObservation struct {

	// The id of auto snapshot policy for data disk.
	AutoSnapshotPolicyID *string `json:"autoSnapshotPolicyId,omitempty" tf:"auto_snapshot_policy_id,omitempty"`

	// Category of data disk. The parameter value options are ephemeral_ssd, cloud_efficiency, cloud_ssd and cloud.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Whether to delete data disks attached on ecs when release ecs instance. Optional value: true or false, default to true.
	DeleteWithInstance *bool `json:"deleteWithInstance,omitempty" tf:"delete_with_instance,omitempty"`

	// The description of data disk N. Valid values of N: 1 to 16. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The mount point of data disk N. Valid values of N: 1 to 16. If this parameter is not specified, the system automatically allocates a mount point to created ECS instances. The name of the mount point ranges from /dev/xvdb to /dev/xvdz in alphabetical order.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Specifies whether data disk N is to be encrypted. Valid values of N: 1 to 16. Valid values: true: encrypted, false: not encrypted. Default value: false.
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// The CMK ID for data disk N. Valid values of N: 1 to 16.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The name of data disk N. Valid values of N: 1 to 16. It must be 2 to 128 characters in length. It must start with a letter and cannot start with http:// or https://. It can contain letters, digits, colons (:), underscores (_), and hyphens (-). Default value: null.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The performance level of the ESSD used as data disk.
	PerformanceLevel *string `json:"performanceLevel,omitempty" tf:"performance_level,omitempty"`

	// Size of data disk, in GB. The value ranges [5,2000] for a cloud disk, [5,1024] for an ephemeral disk, [5,800] for an ephemeral_ssd disk, [20,32768] for cloud_efficiency, cloud_ssd, cloud_essd disk.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Snapshot used for creating the data disk. If this parameter is specified, the size parameter is neglected, and the size of the created disk is the size of the snapshot.
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type DataDiskParameters struct {

	// The id of auto snapshot policy for data disk.
	// +kubebuilder:validation:Optional
	AutoSnapshotPolicyID *string `json:"autoSnapshotPolicyId,omitempty" tf:"auto_snapshot_policy_id,omitempty"`

	// Category of data disk. The parameter value options are ephemeral_ssd, cloud_efficiency, cloud_ssd and cloud.
	// +kubebuilder:validation:Optional
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Whether to delete data disks attached on ecs when release ecs instance. Optional value: true or false, default to true.
	// +kubebuilder:validation:Optional
	DeleteWithInstance *bool `json:"deleteWithInstance,omitempty" tf:"delete_with_instance,omitempty"`

	// The description of data disk N. Valid values of N: 1 to 16. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The mount point of data disk N. Valid values of N: 1 to 16. If this parameter is not specified, the system automatically allocates a mount point to created ECS instances. The name of the mount point ranges from /dev/xvdb to /dev/xvdz in alphabetical order.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Specifies whether data disk N is to be encrypted. Valid values of N: 1 to 16. Valid values: true: encrypted, false: not encrypted. Default value: false.
	// +kubebuilder:validation:Optional
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// The CMK ID for data disk N. Valid values of N: 1 to 16.
	// +kubebuilder:validation:Optional
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The name of data disk N. Valid values of N: 1 to 16. It must be 2 to 128 characters in length. It must start with a letter and cannot start with http:// or https://. It can contain letters, digits, colons (:), underscores (_), and hyphens (-). Default value: null.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The performance level of the ESSD used as data disk.
	// +kubebuilder:validation:Optional
	PerformanceLevel *string `json:"performanceLevel,omitempty" tf:"performance_level,omitempty"`

	// Size of data disk, in GB. The value ranges [5,2000] for a cloud disk, [5,1024] for an ephemeral disk, [5,800] for an ephemeral_ssd disk, [20,32768] for cloud_efficiency, cloud_ssd, cloud_essd disk.
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Snapshot used for creating the data disk. If this parameter is specified, the size parameter is neglected, and the size of the created disk is the size of the snapshot.
	// +kubebuilder:validation:Optional
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type InstancePatternInfoInitParameters struct {

	// The number of vCPUs that are specified for an instance type in instancePatternInfo.
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// The instance family level in instancePatternInfo.
	InstanceFamilyLevel *string `json:"instanceFamilyLevel,omitempty" tf:"instance_family_level,omitempty"`

	// The maximum hourly price for a pay-as-you-go instance or a preemptible instance in instancePatternInfo.
	MaxPrice *float64 `json:"maxPrice,omitempty" tf:"max_price,omitempty"`

	// The memory size that is specified for an instance type in instancePatternInfo.
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`
}

type InstancePatternInfoObservation struct {

	// The number of vCPUs that are specified for an instance type in instancePatternInfo.
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// The instance family level in instancePatternInfo.
	InstanceFamilyLevel *string `json:"instanceFamilyLevel,omitempty" tf:"instance_family_level,omitempty"`

	// The maximum hourly price for a pay-as-you-go instance or a preemptible instance in instancePatternInfo.
	MaxPrice *float64 `json:"maxPrice,omitempty" tf:"max_price,omitempty"`

	// The memory size that is specified for an instance type in instancePatternInfo.
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`
}

type InstancePatternInfoParameters struct {

	// The number of vCPUs that are specified for an instance type in instancePatternInfo.
	// +kubebuilder:validation:Optional
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// The instance family level in instancePatternInfo.
	// +kubebuilder:validation:Optional
	InstanceFamilyLevel *string `json:"instanceFamilyLevel,omitempty" tf:"instance_family_level,omitempty"`

	// The maximum hourly price for a pay-as-you-go instance or a preemptible instance in instancePatternInfo.
	// +kubebuilder:validation:Optional
	MaxPrice *float64 `json:"maxPrice,omitempty" tf:"max_price,omitempty"`

	// The memory size that is specified for an instance type in instancePatternInfo.
	// +kubebuilder:validation:Optional
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`
}

type InstanceTypeOverrideInitParameters struct {

	// The is specified for an instance type in instanceTypeOverride.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The weight of instance type in instanceTypeOverride.
	WeightedCapacity *float64 `json:"weightedCapacity,omitempty" tf:"weighted_capacity,omitempty"`
}

type InstanceTypeOverrideObservation struct {

	// The is specified for an instance type in instanceTypeOverride.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The weight of instance type in instanceTypeOverride.
	WeightedCapacity *float64 `json:"weightedCapacity,omitempty" tf:"weighted_capacity,omitempty"`
}

type InstanceTypeOverrideParameters struct {

	// The is specified for an instance type in instanceTypeOverride.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The weight of instance type in instanceTypeOverride.
	// +kubebuilder:validation:Optional
	WeightedCapacity *float64 `json:"weightedCapacity,omitempty" tf:"weighted_capacity,omitempty"`
}

type ScalingConfigurationInitParameters struct {

	// Whether active current scaling configuration in the specified scaling group. Default to false.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Performance mode of the t5 burstable instance. Valid values: 'Standard', 'Unlimited'.
	CreditSpecification *string `json:"creditSpecification,omitempty" tf:"credit_specification,omitempty"`

	// DataDisk mappings to attach to ecs instance. See data_disk below for details.
	DataDisk []DataDiskInitParameters `json:"dataDisk,omitempty" tf:"data_disk,omitempty"`

	// Whether enable the specified scaling group(make it active) to which the current scaling configuration belongs.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The last scaling configuration will be deleted forcibly with deleting its scaling group. Default to false.
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// Hostname of an ECS instance.
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// ID of an image file, indicating the image resource selected when an instance is enabled.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Name of an image file, indicating the image resource selected when an instance is enabled.
	ImageName *string `json:"imageName,omitempty" tf:"image_name,omitempty"`

	// (Deprecated) It has been deprecated from version 1.6.0. New resource alicloud_ess_attachment replaces it.
	InstanceIds []*string `json:"instanceIds,omitempty" tf:"instance_ids,omitempty"`

	// Name of an ECS instance. Default to "ESS-Instance". It is valid from version 1.7.1.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// intelligent configuration mode. In this mode, you only need to specify the number of vCPUs, memory size, instance family, and maximum price. The system selects an instance type that is provided at the lowest price based on your configurations to create ECS instances. This mode is available only for scaling groups that reside in virtual private clouds (VPCs). This mode helps reduce the failures of scale-out activities caused by insufficient inventory of instance types.  See instance_pattern_info below for details.
	InstancePatternInfo []InstancePatternInfoInitParameters `json:"instancePatternInfo,omitempty" tf:"instance_pattern_info,omitempty"`

	// Resource type of an ECS instance.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// specify the weight of instance type.  See instance_type_override below for details.
	InstanceTypeOverride []InstanceTypeOverrideInitParameters `json:"instanceTypeOverride,omitempty" tf:"instance_type_override,omitempty"`

	// Resource types of an ECS instance.
	InstanceTypes []*string `json:"instanceTypes,omitempty" tf:"instance_types,omitempty"`

	// Network billing type, Values: PayByBandwidth or PayByTraffic. Default to PayByBandwidth.
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// Maximum incoming bandwidth from the public network, measured in Mbps (Mega bit per second). The value range is [1,200].
	InternetMaxBandwidthIn *float64 `json:"internetMaxBandwidthIn,omitempty" tf:"internet_max_bandwidth_in,omitempty"`

	// Maximum outgoing bandwidth from the public network, measured in Mbps (Mega bit per second). The value range for PayByBandwidth is [0,1024].
	InternetMaxBandwidthOut *float64 `json:"internetMaxBandwidthOut,omitempty" tf:"internet_max_bandwidth_out,omitempty"`

	// (Deprecated) It has been deprecated on instance resource. All the launched alicloud instances will be I/O optimized.
	IoOptimized *string `json:"ioOptimized,omitempty" tf:"io_optimized,omitempty"`

	// Whether to use outdated instance type. Default to false.
	IsOutdated *bool `json:"isOutdated,omitempty" tf:"is_outdated,omitempty"`

	// An KMS encrypts password used to a db account. If the password is filled in, this field will be ignored.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a db account with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The name of key pair that can login ECS instance successfully without password. If it is specified, the password would be invalid.
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Indicates whether to overwrite the existing data. Default to false.
	Override *bool `json:"override,omitempty" tf:"override,omitempty"`

	// The password of the ECS instance. The password must be 8 to 30 characters in length. It must contains at least three of the following character types: uppercase letters, lowercase letters, digits, and special characters. Special characters include () ~!@#$%^&*-_+=\|{}[]:;'<>,.?/, The password of Windows-based instances cannot start with a forward slash (/).
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// Specifies whether to use the password that is predefined in the image. If the PasswordInherit parameter is set to true, the password and kms_encrypted_password will be ignored. You must ensure that the selected image has a password configured.
	PasswordInherit *bool `json:"passwordInherit,omitempty" tf:"password_inherit,omitempty"`

	// ID of resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Instance RAM role name. The name is provided and maintained by RAM. You can use alicloud_ram_role to create a new one.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// Name shown for the scheduled task. which must contain 2-64 characters (English or Chinese), starting with numbers, English letters or Chinese characters, and can contain number, underscores _, hypens -, and decimal point .. If this parameter value is not specified, the default value is ScalingConfigurationId.
	ScalingConfigurationName *string `json:"scalingConfigurationName,omitempty" tf:"scaling_configuration_name,omitempty"`

	// ID of the scaling group of a scaling configuration.
	ScalingGroupID *string `json:"scalingGroupId,omitempty" tf:"scaling_group_id,omitempty"`

	// ID of the security group used to create new instance. It is conflict with security_group_ids.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// List IDs of the security group used to create new instances. It is conflict with security_group_id.
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// Sets the maximum price hourly for instance types. See spot_price_limit below for details.
	SpotPriceLimit []SpotPriceLimitInitParameters `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The spot strategy for a Pay-As-You-Go instance. Valid values: NoSpot, SpotAsPriceGo, SpotWithPriceLimit.
	SpotStrategy *string `json:"spotStrategy,omitempty" tf:"spot_strategy,omitempty"`

	// The another scaling configuration which will be active automatically and replace current configuration when setting active to 'false'. It is invalid when active is 'true'.
	Substitute *string `json:"substitute,omitempty" tf:"substitute,omitempty"`

	// The id of auto snapshot policy for system disk.
	SystemDiskAutoSnapshotPolicyID *string `json:"systemDiskAutoSnapshotPolicyId,omitempty" tf:"system_disk_auto_snapshot_policy_id,omitempty"`

	// Category of the system disk. The parameter value options are ephemeral_ssd, cloud_efficiency, cloud_ssd, cloud_essd and cloud. cloud only is used to some no I/O optimized instance. Default to cloud_efficiency.
	SystemDiskCategory *string `json:"systemDiskCategory,omitempty" tf:"system_disk_category,omitempty"`

	// The description of the system disk. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	SystemDiskDescription *string `json:"systemDiskDescription,omitempty" tf:"system_disk_description,omitempty"`

	// Whether to encrypt the system disk.
	SystemDiskEncrypted *bool `json:"systemDiskEncrypted,omitempty" tf:"system_disk_encrypted,omitempty"`

	// The name of the system disk. It must be 2 to 128 characters in length. It must start with a letter and cannot start with http:// or https://. It can contain letters, digits, colons (:), underscores (_), and hyphens (-). Default value: null.
	SystemDiskName *string `json:"systemDiskName,omitempty" tf:"system_disk_name,omitempty"`

	// The performance level of the ESSD used as the system disk.
	SystemDiskPerformanceLevel *string `json:"systemDiskPerformanceLevel,omitempty" tf:"system_disk_performance_level,omitempty"`

	// Size of system disk, in GiB. Optional values: cloud: 20-500, cloud_efficiency: 20-500, cloud_ssd: 20-500, ephemeral_ssd: 20-500 The default value is max{40, ImageSize}. If this parameter is set, the system disk size must be greater than or equal to max{40, ImageSize}.
	SystemDiskSize *float64 `json:"systemDiskSize,omitempty" tf:"system_disk_size,omitempty"`

	// A mapping of tags to assign to the resource. It will be applied for ECS instances finally.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User-defined data to customize the startup behaviors of the ECS instance and to pass data into the ECS instance.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type ScalingConfigurationObservation struct {

	// Whether active current scaling configuration in the specified scaling group. Default to false.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Performance mode of the t5 burstable instance. Valid values: 'Standard', 'Unlimited'.
	CreditSpecification *string `json:"creditSpecification,omitempty" tf:"credit_specification,omitempty"`

	// DataDisk mappings to attach to ecs instance. See data_disk below for details.
	DataDisk []DataDiskObservation `json:"dataDisk,omitempty" tf:"data_disk,omitempty"`

	// Whether enable the specified scaling group(make it active) to which the current scaling configuration belongs.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The last scaling configuration will be deleted forcibly with deleting its scaling group. Default to false.
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// Hostname of an ECS instance.
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// The scaling configuration ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ID of an image file, indicating the image resource selected when an instance is enabled.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Name of an image file, indicating the image resource selected when an instance is enabled.
	ImageName *string `json:"imageName,omitempty" tf:"image_name,omitempty"`

	// (Deprecated) It has been deprecated from version 1.6.0. New resource alicloud_ess_attachment replaces it.
	InstanceIds []*string `json:"instanceIds,omitempty" tf:"instance_ids,omitempty"`

	// Name of an ECS instance. Default to "ESS-Instance". It is valid from version 1.7.1.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// intelligent configuration mode. In this mode, you only need to specify the number of vCPUs, memory size, instance family, and maximum price. The system selects an instance type that is provided at the lowest price based on your configurations to create ECS instances. This mode is available only for scaling groups that reside in virtual private clouds (VPCs). This mode helps reduce the failures of scale-out activities caused by insufficient inventory of instance types.  See instance_pattern_info below for details.
	InstancePatternInfo []InstancePatternInfoObservation `json:"instancePatternInfo,omitempty" tf:"instance_pattern_info,omitempty"`

	// Resource type of an ECS instance.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// specify the weight of instance type.  See instance_type_override below for details.
	InstanceTypeOverride []InstanceTypeOverrideObservation `json:"instanceTypeOverride,omitempty" tf:"instance_type_override,omitempty"`

	// Resource types of an ECS instance.
	InstanceTypes []*string `json:"instanceTypes,omitempty" tf:"instance_types,omitempty"`

	// Network billing type, Values: PayByBandwidth or PayByTraffic. Default to PayByBandwidth.
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// Maximum incoming bandwidth from the public network, measured in Mbps (Mega bit per second). The value range is [1,200].
	InternetMaxBandwidthIn *float64 `json:"internetMaxBandwidthIn,omitempty" tf:"internet_max_bandwidth_in,omitempty"`

	// Maximum outgoing bandwidth from the public network, measured in Mbps (Mega bit per second). The value range for PayByBandwidth is [0,1024].
	InternetMaxBandwidthOut *float64 `json:"internetMaxBandwidthOut,omitempty" tf:"internet_max_bandwidth_out,omitempty"`

	// (Deprecated) It has been deprecated on instance resource. All the launched alicloud instances will be I/O optimized.
	IoOptimized *string `json:"ioOptimized,omitempty" tf:"io_optimized,omitempty"`

	// Whether to use outdated instance type. Default to false.
	IsOutdated *bool `json:"isOutdated,omitempty" tf:"is_outdated,omitempty"`

	// An KMS encrypts password used to a db account. If the password is filled in, this field will be ignored.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a db account with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The name of key pair that can login ECS instance successfully without password. If it is specified, the password would be invalid.
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Indicates whether to overwrite the existing data. Default to false.
	Override *bool `json:"override,omitempty" tf:"override,omitempty"`

	// The password of the ECS instance. The password must be 8 to 30 characters in length. It must contains at least three of the following character types: uppercase letters, lowercase letters, digits, and special characters. Special characters include () ~!@#$%^&*-_+=\|{}[]:;'<>,.?/, The password of Windows-based instances cannot start with a forward slash (/).
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// Specifies whether to use the password that is predefined in the image. If the PasswordInherit parameter is set to true, the password and kms_encrypted_password will be ignored. You must ensure that the selected image has a password configured.
	PasswordInherit *bool `json:"passwordInherit,omitempty" tf:"password_inherit,omitempty"`

	// ID of resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Instance RAM role name. The name is provided and maintained by RAM. You can use alicloud_ram_role to create a new one.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// Name shown for the scheduled task. which must contain 2-64 characters (English or Chinese), starting with numbers, English letters or Chinese characters, and can contain number, underscores _, hypens -, and decimal point .. If this parameter value is not specified, the default value is ScalingConfigurationId.
	ScalingConfigurationName *string `json:"scalingConfigurationName,omitempty" tf:"scaling_configuration_name,omitempty"`

	// ID of the scaling group of a scaling configuration.
	ScalingGroupID *string `json:"scalingGroupId,omitempty" tf:"scaling_group_id,omitempty"`

	// ID of the security group used to create new instance. It is conflict with security_group_ids.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// List IDs of the security group used to create new instances. It is conflict with security_group_id.
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// Sets the maximum price hourly for instance types. See spot_price_limit below for details.
	SpotPriceLimit []SpotPriceLimitObservation `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The spot strategy for a Pay-As-You-Go instance. Valid values: NoSpot, SpotAsPriceGo, SpotWithPriceLimit.
	SpotStrategy *string `json:"spotStrategy,omitempty" tf:"spot_strategy,omitempty"`

	// The another scaling configuration which will be active automatically and replace current configuration when setting active to 'false'. It is invalid when active is 'true'.
	Substitute *string `json:"substitute,omitempty" tf:"substitute,omitempty"`

	// The id of auto snapshot policy for system disk.
	SystemDiskAutoSnapshotPolicyID *string `json:"systemDiskAutoSnapshotPolicyId,omitempty" tf:"system_disk_auto_snapshot_policy_id,omitempty"`

	// Category of the system disk. The parameter value options are ephemeral_ssd, cloud_efficiency, cloud_ssd, cloud_essd and cloud. cloud only is used to some no I/O optimized instance. Default to cloud_efficiency.
	SystemDiskCategory *string `json:"systemDiskCategory,omitempty" tf:"system_disk_category,omitempty"`

	// The description of the system disk. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	SystemDiskDescription *string `json:"systemDiskDescription,omitempty" tf:"system_disk_description,omitempty"`

	// Whether to encrypt the system disk.
	SystemDiskEncrypted *bool `json:"systemDiskEncrypted,omitempty" tf:"system_disk_encrypted,omitempty"`

	// The name of the system disk. It must be 2 to 128 characters in length. It must start with a letter and cannot start with http:// or https://. It can contain letters, digits, colons (:), underscores (_), and hyphens (-). Default value: null.
	SystemDiskName *string `json:"systemDiskName,omitempty" tf:"system_disk_name,omitempty"`

	// The performance level of the ESSD used as the system disk.
	SystemDiskPerformanceLevel *string `json:"systemDiskPerformanceLevel,omitempty" tf:"system_disk_performance_level,omitempty"`

	// Size of system disk, in GiB. Optional values: cloud: 20-500, cloud_efficiency: 20-500, cloud_ssd: 20-500, ephemeral_ssd: 20-500 The default value is max{40, ImageSize}. If this parameter is set, the system disk size must be greater than or equal to max{40, ImageSize}.
	SystemDiskSize *float64 `json:"systemDiskSize,omitempty" tf:"system_disk_size,omitempty"`

	// A mapping of tags to assign to the resource. It will be applied for ECS instances finally.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User-defined data to customize the startup behaviors of the ECS instance and to pass data into the ECS instance.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type ScalingConfigurationParameters struct {

	// Whether active current scaling configuration in the specified scaling group. Default to false.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Performance mode of the t5 burstable instance. Valid values: 'Standard', 'Unlimited'.
	// +kubebuilder:validation:Optional
	CreditSpecification *string `json:"creditSpecification,omitempty" tf:"credit_specification,omitempty"`

	// DataDisk mappings to attach to ecs instance. See data_disk below for details.
	// +kubebuilder:validation:Optional
	DataDisk []DataDiskParameters `json:"dataDisk,omitempty" tf:"data_disk,omitempty"`

	// Whether enable the specified scaling group(make it active) to which the current scaling configuration belongs.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The last scaling configuration will be deleted forcibly with deleting its scaling group. Default to false.
	// +kubebuilder:validation:Optional
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// Hostname of an ECS instance.
	// +kubebuilder:validation:Optional
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// ID of an image file, indicating the image resource selected when an instance is enabled.
	// +kubebuilder:validation:Optional
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Name of an image file, indicating the image resource selected when an instance is enabled.
	// +kubebuilder:validation:Optional
	ImageName *string `json:"imageName,omitempty" tf:"image_name,omitempty"`

	// (Deprecated) It has been deprecated from version 1.6.0. New resource alicloud_ess_attachment replaces it.
	// +kubebuilder:validation:Optional
	InstanceIds []*string `json:"instanceIds,omitempty" tf:"instance_ids,omitempty"`

	// Name of an ECS instance. Default to "ESS-Instance". It is valid from version 1.7.1.
	// +kubebuilder:validation:Optional
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// intelligent configuration mode. In this mode, you only need to specify the number of vCPUs, memory size, instance family, and maximum price. The system selects an instance type that is provided at the lowest price based on your configurations to create ECS instances. This mode is available only for scaling groups that reside in virtual private clouds (VPCs). This mode helps reduce the failures of scale-out activities caused by insufficient inventory of instance types.  See instance_pattern_info below for details.
	// +kubebuilder:validation:Optional
	InstancePatternInfo []InstancePatternInfoParameters `json:"instancePatternInfo,omitempty" tf:"instance_pattern_info,omitempty"`

	// Resource type of an ECS instance.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// specify the weight of instance type.  See instance_type_override below for details.
	// +kubebuilder:validation:Optional
	InstanceTypeOverride []InstanceTypeOverrideParameters `json:"instanceTypeOverride,omitempty" tf:"instance_type_override,omitempty"`

	// Resource types of an ECS instance.
	// +kubebuilder:validation:Optional
	InstanceTypes []*string `json:"instanceTypes,omitempty" tf:"instance_types,omitempty"`

	// Network billing type, Values: PayByBandwidth or PayByTraffic. Default to PayByBandwidth.
	// +kubebuilder:validation:Optional
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// Maximum incoming bandwidth from the public network, measured in Mbps (Mega bit per second). The value range is [1,200].
	// +kubebuilder:validation:Optional
	InternetMaxBandwidthIn *float64 `json:"internetMaxBandwidthIn,omitempty" tf:"internet_max_bandwidth_in,omitempty"`

	// Maximum outgoing bandwidth from the public network, measured in Mbps (Mega bit per second). The value range for PayByBandwidth is [0,1024].
	// +kubebuilder:validation:Optional
	InternetMaxBandwidthOut *float64 `json:"internetMaxBandwidthOut,omitempty" tf:"internet_max_bandwidth_out,omitempty"`

	// (Deprecated) It has been deprecated on instance resource. All the launched alicloud instances will be I/O optimized.
	// +kubebuilder:validation:Optional
	IoOptimized *string `json:"ioOptimized,omitempty" tf:"io_optimized,omitempty"`

	// Whether to use outdated instance type. Default to false.
	// +kubebuilder:validation:Optional
	IsOutdated *bool `json:"isOutdated,omitempty" tf:"is_outdated,omitempty"`

	// An KMS encrypts password used to a db account. If the password is filled in, this field will be ignored.
	// +kubebuilder:validation:Optional
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a db account with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The name of key pair that can login ECS instance successfully without password. If it is specified, the password would be invalid.
	// +kubebuilder:validation:Optional
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Indicates whether to overwrite the existing data. Default to false.
	// +kubebuilder:validation:Optional
	Override *bool `json:"override,omitempty" tf:"override,omitempty"`

	// The password of the ECS instance. The password must be 8 to 30 characters in length. It must contains at least three of the following character types: uppercase letters, lowercase letters, digits, and special characters. Special characters include () ~!@#$%^&*-_+=\|{}[]:;'<>,.?/, The password of Windows-based instances cannot start with a forward slash (/).
	// +kubebuilder:validation:Optional
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// Specifies whether to use the password that is predefined in the image. If the PasswordInherit parameter is set to true, the password and kms_encrypted_password will be ignored. You must ensure that the selected image has a password configured.
	// +kubebuilder:validation:Optional
	PasswordInherit *bool `json:"passwordInherit,omitempty" tf:"password_inherit,omitempty"`

	// ID of resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Instance RAM role name. The name is provided and maintained by RAM. You can use alicloud_ram_role to create a new one.
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// Name shown for the scheduled task. which must contain 2-64 characters (English or Chinese), starting with numbers, English letters or Chinese characters, and can contain number, underscores _, hypens -, and decimal point .. If this parameter value is not specified, the default value is ScalingConfigurationId.
	// +kubebuilder:validation:Optional
	ScalingConfigurationName *string `json:"scalingConfigurationName,omitempty" tf:"scaling_configuration_name,omitempty"`

	// ID of the scaling group of a scaling configuration.
	// +kubebuilder:validation:Optional
	ScalingGroupID *string `json:"scalingGroupId,omitempty" tf:"scaling_group_id,omitempty"`

	// ID of the security group used to create new instance. It is conflict with security_group_ids.
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// List IDs of the security group used to create new instances. It is conflict with security_group_id.
	// +kubebuilder:validation:Optional
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// Sets the maximum price hourly for instance types. See spot_price_limit below for details.
	// +kubebuilder:validation:Optional
	SpotPriceLimit []SpotPriceLimitParameters `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The spot strategy for a Pay-As-You-Go instance. Valid values: NoSpot, SpotAsPriceGo, SpotWithPriceLimit.
	// +kubebuilder:validation:Optional
	SpotStrategy *string `json:"spotStrategy,omitempty" tf:"spot_strategy,omitempty"`

	// The another scaling configuration which will be active automatically and replace current configuration when setting active to 'false'. It is invalid when active is 'true'.
	// +kubebuilder:validation:Optional
	Substitute *string `json:"substitute,omitempty" tf:"substitute,omitempty"`

	// The id of auto snapshot policy for system disk.
	// +kubebuilder:validation:Optional
	SystemDiskAutoSnapshotPolicyID *string `json:"systemDiskAutoSnapshotPolicyId,omitempty" tf:"system_disk_auto_snapshot_policy_id,omitempty"`

	// Category of the system disk. The parameter value options are ephemeral_ssd, cloud_efficiency, cloud_ssd, cloud_essd and cloud. cloud only is used to some no I/O optimized instance. Default to cloud_efficiency.
	// +kubebuilder:validation:Optional
	SystemDiskCategory *string `json:"systemDiskCategory,omitempty" tf:"system_disk_category,omitempty"`

	// The description of the system disk. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	SystemDiskDescription *string `json:"systemDiskDescription,omitempty" tf:"system_disk_description,omitempty"`

	// Whether to encrypt the system disk.
	// +kubebuilder:validation:Optional
	SystemDiskEncrypted *bool `json:"systemDiskEncrypted,omitempty" tf:"system_disk_encrypted,omitempty"`

	// The name of the system disk. It must be 2 to 128 characters in length. It must start with a letter and cannot start with http:// or https://. It can contain letters, digits, colons (:), underscores (_), and hyphens (-). Default value: null.
	// +kubebuilder:validation:Optional
	SystemDiskName *string `json:"systemDiskName,omitempty" tf:"system_disk_name,omitempty"`

	// The performance level of the ESSD used as the system disk.
	// +kubebuilder:validation:Optional
	SystemDiskPerformanceLevel *string `json:"systemDiskPerformanceLevel,omitempty" tf:"system_disk_performance_level,omitempty"`

	// Size of system disk, in GiB. Optional values: cloud: 20-500, cloud_efficiency: 20-500, cloud_ssd: 20-500, ephemeral_ssd: 20-500 The default value is max{40, ImageSize}. If this parameter is set, the system disk size must be greater than or equal to max{40, ImageSize}.
	// +kubebuilder:validation:Optional
	SystemDiskSize *float64 `json:"systemDiskSize,omitempty" tf:"system_disk_size,omitempty"`

	// A mapping of tags to assign to the resource. It will be applied for ECS instances finally.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User-defined data to customize the startup behaviors of the ECS instance and to pass data into the ECS instance.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type SpotPriceLimitInitParameters struct {

	// Resource type of an ECS instance.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Price limit hourly of instance type, 2 decimals is allowed at most.
	PriceLimit *float64 `json:"priceLimit,omitempty" tf:"price_limit,omitempty"`
}

type SpotPriceLimitObservation struct {

	// Resource type of an ECS instance.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Price limit hourly of instance type, 2 decimals is allowed at most.
	PriceLimit *float64 `json:"priceLimit,omitempty" tf:"price_limit,omitempty"`
}

type SpotPriceLimitParameters struct {

	// Resource type of an ECS instance.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Price limit hourly of instance type, 2 decimals is allowed at most.
	// +kubebuilder:validation:Optional
	PriceLimit *float64 `json:"priceLimit,omitempty" tf:"price_limit,omitempty"`
}

// ScalingConfigurationSpec defines the desired state of ScalingConfiguration
type ScalingConfigurationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScalingConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScalingConfigurationInitParameters `json:"initProvider,omitempty"`
}

// ScalingConfigurationStatus defines the observed state of ScalingConfiguration.
type ScalingConfigurationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScalingConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScalingConfiguration is the Schema for the ScalingConfigurations API. Provides an ESS scaling configuration resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ScalingConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scalingGroupId) || (has(self.initProvider) && has(self.initProvider.scalingGroupId))",message="spec.forProvider.scalingGroupId is a required parameter"
	Spec   ScalingConfigurationSpec   `json:"spec"`
	Status ScalingConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScalingConfigurationList contains a list of ScalingConfigurations
type ScalingConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScalingConfiguration `json:"items"`
}

// Repository type metadata.
var (
	ScalingConfiguration_Kind             = "ScalingConfiguration"
	ScalingConfiguration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScalingConfiguration_Kind}.String()
	ScalingConfiguration_KindAPIVersion   = ScalingConfiguration_Kind + "." + CRDGroupVersion.String()
	ScalingConfiguration_GroupVersionKind = CRDGroupVersion.WithKind(ScalingConfiguration_Kind)
)

func init() {
	SchemeBuilder.Register(&ScalingConfiguration{}, &ScalingConfigurationList{})
}
