// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LaunchTemplateOverrideInitParameters struct {

	// The instance type in launchTemplateOverride.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The maximum bid price of instance type in launchTemplateOverride.
	SpotPriceLimit *float64 `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The weight of the instance type in launchTemplateOverride.
	WeightedCapacity *float64 `json:"weightedCapacity,omitempty" tf:"weighted_capacity,omitempty"`
}

type LaunchTemplateOverrideObservation struct {

	// The instance type in launchTemplateOverride.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The maximum bid price of instance type in launchTemplateOverride.
	SpotPriceLimit *float64 `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The weight of the instance type in launchTemplateOverride.
	WeightedCapacity *float64 `json:"weightedCapacity,omitempty" tf:"weighted_capacity,omitempty"`
}

type LaunchTemplateOverrideParameters struct {

	// The instance type in launchTemplateOverride.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The maximum bid price of instance type in launchTemplateOverride.
	// +kubebuilder:validation:Optional
	SpotPriceLimit *float64 `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The weight of the instance type in launchTemplateOverride.
	// +kubebuilder:validation:Optional
	WeightedCapacity *float64 `json:"weightedCapacity,omitempty" tf:"weighted_capacity,omitempty"`
}

type ScalingGroupInitParameters struct {

	// If an RDS instance is specified in the scaling group, the scaling group automatically attaches the Intranet IP addresses of its ECS instances to the RDS access whitelist.
	// +listType=set
	DBInstanceIds []*string `json:"dbInstanceIds,omitempty" tf:"db_instance_ids,omitempty"`

	// Default cool-down time (in seconds) of the scaling group. Value range: [0, 86400]. The default value is 300s.
	DefaultCooldown *float64 `json:"defaultCooldown,omitempty" tf:"default_cooldown,omitempty"`

	// Expected number of ECS instances in the scaling group. Value range: [min_size, max_size].
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// Specifies whether the scaling group deletion protection is enabled. true or false, Default value: false.
	GroupDeletionProtection *bool `json:"groupDeletionProtection,omitempty" tf:"group_deletion_protection,omitempty"`

	// Resource type within scaling group. Optional values: ECS, ECI. Default to ECS.
	GroupType *string `json:"groupType,omitempty" tf:"group_type,omitempty"`

	// Resource type within scaling group. Optional values: ECS, NONE. Default to ECS.
	HealthCheckType *string `json:"healthCheckType,omitempty" tf:"health_check_type,omitempty"`

	// Instance launch template ID, scaling group obtains launch configuration from instance launch template, see Launch Template. Creating scaling group from launch template enable group automatically.
	LaunchTemplateID *string `json:"launchTemplateId,omitempty" tf:"launch_template_id,omitempty"`

	// The details of the instance types that are specified by using the Extend Instance Type of Launch Template feature..  See launch_template_override below for details.
	LaunchTemplateOverride []LaunchTemplateOverrideInitParameters `json:"launchTemplateOverride,omitempty" tf:"launch_template_override,omitempty"`

	// The version number of the launch template. Valid values are the version number, Latest, or Default, Default value: Default.
	LaunchTemplateVersion *string `json:"launchTemplateVersion,omitempty" tf:"launch_template_version,omitempty"`

	// If a Server Load Balancer instance is specified in the scaling group, the scaling group automatically attaches its ECS instances to the Server Load Balancer instance.
	// +listType=set
	LoadbalancerIds []*string `json:"loadbalancerIds,omitempty" tf:"loadbalancer_ids,omitempty"`

	// Maximum number of ECS instances in the scaling group. Value range: [0, 2000].
	// NOTE: From version 1.204.1, max_size can be set to 2000.
	MaxSize *float64 `json:"maxSize,omitempty" tf:"max_size,omitempty"`

	// Minimum number of ECS instances in the scaling group. Value range: [0, 2000].
	// NOTE: From version 1.204.1, min_size can be set to 2000.
	MinSize *float64 `json:"minSize,omitempty" tf:"min_size,omitempty"`

	// Multi-AZ scaling group ECS instance expansion and contraction strategy. PRIORITY, BALANCE or COST_OPTIMIZED(Available since v1.54.0).
	MultiAzPolicy *string `json:"multiAzPolicy,omitempty" tf:"multi_az_policy,omitempty"`

	// The minimum amount of the Auto Scaling group's capacity that must be fulfilled by On-Demand Instances. This base portion is provisioned first as your group scales.
	OnDemandBaseCapacity *float64 `json:"onDemandBaseCapacity,omitempty" tf:"on_demand_base_capacity,omitempty"`

	// Controls the percentages of On-Demand Instances and Spot Instances for your additional capacity beyond OnDemandBaseCapacity.
	OnDemandPercentageAboveBaseCapacity *float64 `json:"onDemandPercentageAboveBaseCapacity,omitempty" tf:"on_demand_percentage_above_base_capacity,omitempty"`

	// Set or unset instances within group into protected status.
	// +listType=set
	ProtectedInstances []*string `json:"protectedInstances,omitempty" tf:"protected_instances,omitempty"`

	// RemovalPolicy is used to select the ECS instances you want to remove from the scaling group when multiple candidates for removal exist. Optional values:
	RemovalPolicies []*string `json:"removalPolicies,omitempty" tf:"removal_policies,omitempty"`

	// Name shown for the scaling group, which must contain 2-64 characters (English or Chinese), starting with numbers, English letters or Chinese characters, and can contain numbers, underscores _, hyphens -, and decimal points .. If this parameter is not specified, the default value is ScalingGroupId.
	ScalingGroupName *string `json:"scalingGroupName,omitempty" tf:"scaling_group_name,omitempty"`

	// The number of Spot pools to use to allocate your Spot capacity. The Spot pools is composed of instance types of lowest price.
	SpotInstancePools *float64 `json:"spotInstancePools,omitempty" tf:"spot_instance_pools,omitempty"`

	// Whether to replace spot instances with newly created spot/onDemand instance when receive a spot recycling message.
	SpotInstanceRemedy *bool `json:"spotInstanceRemedy,omitempty" tf:"spot_instance_remedy,omitempty"`

	// A mapping of tags to assign to the resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Deprecated) It has been deprecated from version 1.7.1 and new field 'vswitch_ids' replaces it.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// List of virtual switch IDs in which the ecs instances to be launched.
	// +listType=set
	VswitchIds []*string `json:"vswitchIds,omitempty" tf:"vswitch_ids,omitempty"`
}

type ScalingGroupObservation struct {

	// If an RDS instance is specified in the scaling group, the scaling group automatically attaches the Intranet IP addresses of its ECS instances to the RDS access whitelist.
	// +listType=set
	DBInstanceIds []*string `json:"dbInstanceIds,omitempty" tf:"db_instance_ids,omitempty"`

	// Default cool-down time (in seconds) of the scaling group. Value range: [0, 86400]. The default value is 300s.
	DefaultCooldown *float64 `json:"defaultCooldown,omitempty" tf:"default_cooldown,omitempty"`

	// Expected number of ECS instances in the scaling group. Value range: [min_size, max_size].
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// Specifies whether the scaling group deletion protection is enabled. true or false, Default value: false.
	GroupDeletionProtection *bool `json:"groupDeletionProtection,omitempty" tf:"group_deletion_protection,omitempty"`

	// Resource type within scaling group. Optional values: ECS, ECI. Default to ECS.
	GroupType *string `json:"groupType,omitempty" tf:"group_type,omitempty"`

	// Resource type within scaling group. Optional values: ECS, NONE. Default to ECS.
	HealthCheckType *string `json:"healthCheckType,omitempty" tf:"health_check_type,omitempty"`

	// The scaling group ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Instance launch template ID, scaling group obtains launch configuration from instance launch template, see Launch Template. Creating scaling group from launch template enable group automatically.
	LaunchTemplateID *string `json:"launchTemplateId,omitempty" tf:"launch_template_id,omitempty"`

	// The details of the instance types that are specified by using the Extend Instance Type of Launch Template feature..  See launch_template_override below for details.
	LaunchTemplateOverride []LaunchTemplateOverrideObservation `json:"launchTemplateOverride,omitempty" tf:"launch_template_override,omitempty"`

	// The version number of the launch template. Valid values are the version number, Latest, or Default, Default value: Default.
	LaunchTemplateVersion *string `json:"launchTemplateVersion,omitempty" tf:"launch_template_version,omitempty"`

	// If a Server Load Balancer instance is specified in the scaling group, the scaling group automatically attaches its ECS instances to the Server Load Balancer instance.
	// +listType=set
	LoadbalancerIds []*string `json:"loadbalancerIds,omitempty" tf:"loadbalancer_ids,omitempty"`

	// Maximum number of ECS instances in the scaling group. Value range: [0, 2000].
	// NOTE: From version 1.204.1, max_size can be set to 2000.
	MaxSize *float64 `json:"maxSize,omitempty" tf:"max_size,omitempty"`

	// Minimum number of ECS instances in the scaling group. Value range: [0, 2000].
	// NOTE: From version 1.204.1, min_size can be set to 2000.
	MinSize *float64 `json:"minSize,omitempty" tf:"min_size,omitempty"`

	// Multi-AZ scaling group ECS instance expansion and contraction strategy. PRIORITY, BALANCE or COST_OPTIMIZED(Available since v1.54.0).
	MultiAzPolicy *string `json:"multiAzPolicy,omitempty" tf:"multi_az_policy,omitempty"`

	// The minimum amount of the Auto Scaling group's capacity that must be fulfilled by On-Demand Instances. This base portion is provisioned first as your group scales.
	OnDemandBaseCapacity *float64 `json:"onDemandBaseCapacity,omitempty" tf:"on_demand_base_capacity,omitempty"`

	// Controls the percentages of On-Demand Instances and Spot Instances for your additional capacity beyond OnDemandBaseCapacity.
	OnDemandPercentageAboveBaseCapacity *float64 `json:"onDemandPercentageAboveBaseCapacity,omitempty" tf:"on_demand_percentage_above_base_capacity,omitempty"`

	// Set or unset instances within group into protected status.
	// +listType=set
	ProtectedInstances []*string `json:"protectedInstances,omitempty" tf:"protected_instances,omitempty"`

	// RemovalPolicy is used to select the ECS instances you want to remove from the scaling group when multiple candidates for removal exist. Optional values:
	RemovalPolicies []*string `json:"removalPolicies,omitempty" tf:"removal_policies,omitempty"`

	// Name shown for the scaling group, which must contain 2-64 characters (English or Chinese), starting with numbers, English letters or Chinese characters, and can contain numbers, underscores _, hyphens -, and decimal points .. If this parameter is not specified, the default value is ScalingGroupId.
	ScalingGroupName *string `json:"scalingGroupName,omitempty" tf:"scaling_group_name,omitempty"`

	// The number of Spot pools to use to allocate your Spot capacity. The Spot pools is composed of instance types of lowest price.
	SpotInstancePools *float64 `json:"spotInstancePools,omitempty" tf:"spot_instance_pools,omitempty"`

	// Whether to replace spot instances with newly created spot/onDemand instance when receive a spot recycling message.
	SpotInstanceRemedy *bool `json:"spotInstanceRemedy,omitempty" tf:"spot_instance_remedy,omitempty"`

	// A mapping of tags to assign to the resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Deprecated) It has been deprecated from version 1.7.1 and new field 'vswitch_ids' replaces it.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// List of virtual switch IDs in which the ecs instances to be launched.
	// +listType=set
	VswitchIds []*string `json:"vswitchIds,omitempty" tf:"vswitch_ids,omitempty"`
}

type ScalingGroupParameters struct {

	// If an RDS instance is specified in the scaling group, the scaling group automatically attaches the Intranet IP addresses of its ECS instances to the RDS access whitelist.
	// +kubebuilder:validation:Optional
	// +listType=set
	DBInstanceIds []*string `json:"dbInstanceIds,omitempty" tf:"db_instance_ids,omitempty"`

	// Default cool-down time (in seconds) of the scaling group. Value range: [0, 86400]. The default value is 300s.
	// +kubebuilder:validation:Optional
	DefaultCooldown *float64 `json:"defaultCooldown,omitempty" tf:"default_cooldown,omitempty"`

	// Expected number of ECS instances in the scaling group. Value range: [min_size, max_size].
	// +kubebuilder:validation:Optional
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// Specifies whether the scaling group deletion protection is enabled. true or false, Default value: false.
	// +kubebuilder:validation:Optional
	GroupDeletionProtection *bool `json:"groupDeletionProtection,omitempty" tf:"group_deletion_protection,omitempty"`

	// Resource type within scaling group. Optional values: ECS, ECI. Default to ECS.
	// +kubebuilder:validation:Optional
	GroupType *string `json:"groupType,omitempty" tf:"group_type,omitempty"`

	// Resource type within scaling group. Optional values: ECS, NONE. Default to ECS.
	// +kubebuilder:validation:Optional
	HealthCheckType *string `json:"healthCheckType,omitempty" tf:"health_check_type,omitempty"`

	// Instance launch template ID, scaling group obtains launch configuration from instance launch template, see Launch Template. Creating scaling group from launch template enable group automatically.
	// +kubebuilder:validation:Optional
	LaunchTemplateID *string `json:"launchTemplateId,omitempty" tf:"launch_template_id,omitempty"`

	// The details of the instance types that are specified by using the Extend Instance Type of Launch Template feature..  See launch_template_override below for details.
	// +kubebuilder:validation:Optional
	LaunchTemplateOverride []LaunchTemplateOverrideParameters `json:"launchTemplateOverride,omitempty" tf:"launch_template_override,omitempty"`

	// The version number of the launch template. Valid values are the version number, Latest, or Default, Default value: Default.
	// +kubebuilder:validation:Optional
	LaunchTemplateVersion *string `json:"launchTemplateVersion,omitempty" tf:"launch_template_version,omitempty"`

	// If a Server Load Balancer instance is specified in the scaling group, the scaling group automatically attaches its ECS instances to the Server Load Balancer instance.
	// +kubebuilder:validation:Optional
	// +listType=set
	LoadbalancerIds []*string `json:"loadbalancerIds,omitempty" tf:"loadbalancer_ids,omitempty"`

	// Maximum number of ECS instances in the scaling group. Value range: [0, 2000].
	// NOTE: From version 1.204.1, max_size can be set to 2000.
	// +kubebuilder:validation:Optional
	MaxSize *float64 `json:"maxSize,omitempty" tf:"max_size,omitempty"`

	// Minimum number of ECS instances in the scaling group. Value range: [0, 2000].
	// NOTE: From version 1.204.1, min_size can be set to 2000.
	// +kubebuilder:validation:Optional
	MinSize *float64 `json:"minSize,omitempty" tf:"min_size,omitempty"`

	// Multi-AZ scaling group ECS instance expansion and contraction strategy. PRIORITY, BALANCE or COST_OPTIMIZED(Available since v1.54.0).
	// +kubebuilder:validation:Optional
	MultiAzPolicy *string `json:"multiAzPolicy,omitempty" tf:"multi_az_policy,omitempty"`

	// The minimum amount of the Auto Scaling group's capacity that must be fulfilled by On-Demand Instances. This base portion is provisioned first as your group scales.
	// +kubebuilder:validation:Optional
	OnDemandBaseCapacity *float64 `json:"onDemandBaseCapacity,omitempty" tf:"on_demand_base_capacity,omitempty"`

	// Controls the percentages of On-Demand Instances and Spot Instances for your additional capacity beyond OnDemandBaseCapacity.
	// +kubebuilder:validation:Optional
	OnDemandPercentageAboveBaseCapacity *float64 `json:"onDemandPercentageAboveBaseCapacity,omitempty" tf:"on_demand_percentage_above_base_capacity,omitempty"`

	// Set or unset instances within group into protected status.
	// +kubebuilder:validation:Optional
	// +listType=set
	ProtectedInstances []*string `json:"protectedInstances,omitempty" tf:"protected_instances,omitempty"`

	// RemovalPolicy is used to select the ECS instances you want to remove from the scaling group when multiple candidates for removal exist. Optional values:
	// +kubebuilder:validation:Optional
	RemovalPolicies []*string `json:"removalPolicies,omitempty" tf:"removal_policies,omitempty"`

	// Name shown for the scaling group, which must contain 2-64 characters (English or Chinese), starting with numbers, English letters or Chinese characters, and can contain numbers, underscores _, hyphens -, and decimal points .. If this parameter is not specified, the default value is ScalingGroupId.
	// +kubebuilder:validation:Optional
	ScalingGroupName *string `json:"scalingGroupName,omitempty" tf:"scaling_group_name,omitempty"`

	// The number of Spot pools to use to allocate your Spot capacity. The Spot pools is composed of instance types of lowest price.
	// +kubebuilder:validation:Optional
	SpotInstancePools *float64 `json:"spotInstancePools,omitempty" tf:"spot_instance_pools,omitempty"`

	// Whether to replace spot instances with newly created spot/onDemand instance when receive a spot recycling message.
	// +kubebuilder:validation:Optional
	SpotInstanceRemedy *bool `json:"spotInstanceRemedy,omitempty" tf:"spot_instance_remedy,omitempty"`

	// A mapping of tags to assign to the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Deprecated) It has been deprecated from version 1.7.1 and new field 'vswitch_ids' replaces it.
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// List of virtual switch IDs in which the ecs instances to be launched.
	// +kubebuilder:validation:Optional
	// +listType=set
	VswitchIds []*string `json:"vswitchIds,omitempty" tf:"vswitch_ids,omitempty"`
}

// ScalingGroupSpec defines the desired state of ScalingGroup
type ScalingGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScalingGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScalingGroupInitParameters `json:"initProvider,omitempty"`
}

// ScalingGroupStatus defines the observed state of ScalingGroup.
type ScalingGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScalingGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScalingGroup is the Schema for the ScalingGroups API. Provides a ESS scaling group resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ScalingGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.maxSize) || (has(self.initProvider) && has(self.initProvider.maxSize))",message="spec.forProvider.maxSize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.minSize) || (has(self.initProvider) && has(self.initProvider.minSize))",message="spec.forProvider.minSize is a required parameter"
	Spec   ScalingGroupSpec   `json:"spec"`
	Status ScalingGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScalingGroupList contains a list of ScalingGroups
type ScalingGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScalingGroup `json:"items"`
}

// Repository type metadata.
var (
	ScalingGroup_Kind             = "ScalingGroup"
	ScalingGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScalingGroup_Kind}.String()
	ScalingGroup_KindAPIVersion   = ScalingGroup_Kind + "." + CRDGroupVersion.String()
	ScalingGroup_GroupVersionKind = CRDGroupVersion.WithKind(ScalingGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ScalingGroup{}, &ScalingGroupList{})
}
