// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DataDisksInitParameters struct {

	// The ID of the automatic snapshot policy applied to the system disk.
	AutoSnapshotPolicyID *string `json:"autoSnapshotPolicyId,omitempty" tf:"auto_snapshot_policy_id,omitempty"`

	// The category of the disk:
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Delete this data disk when the instance is destroyed. It only works on cloud, cloud_efficiency, cloud_essd, cloud_ssd disk. If the category of this data disk was ephemeral_ssd, please don't set this param. Default value: true.
	DeleteWithInstance *bool `json:"deleteWithInstance,omitempty" tf:"delete_with_instance,omitempty"`

	// The description of the data disk.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The mount point of the data disk.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Encrypted the data in this disk. Default value: false.
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// The KMS key ID corresponding to the Nth data disk.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The name of the data disk.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The performance level of the ESSD used as data disk:
	PerformanceLevel *string `json:"performanceLevel,omitempty" tf:"performance_level,omitempty"`

	// The size of the data disk.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// The snapshot ID used to initialize the data disk. If the size specified by snapshot is greater that the size of the disk, use the size specified by snapshot as the size of the data disk.
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type DataDisksObservation struct {

	// The ID of the automatic snapshot policy applied to the system disk.
	AutoSnapshotPolicyID *string `json:"autoSnapshotPolicyId,omitempty" tf:"auto_snapshot_policy_id,omitempty"`

	// The category of the disk:
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Delete this data disk when the instance is destroyed. It only works on cloud, cloud_efficiency, cloud_essd, cloud_ssd disk. If the category of this data disk was ephemeral_ssd, please don't set this param. Default value: true.
	DeleteWithInstance *bool `json:"deleteWithInstance,omitempty" tf:"delete_with_instance,omitempty"`

	// The description of the data disk.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The mount point of the data disk.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Encrypted the data in this disk. Default value: false.
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// The KMS key ID corresponding to the Nth data disk.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The name of the data disk.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The performance level of the ESSD used as data disk:
	PerformanceLevel *string `json:"performanceLevel,omitempty" tf:"performance_level,omitempty"`

	// The size of the data disk.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// The snapshot ID used to initialize the data disk. If the size specified by snapshot is greater that the size of the disk, use the size specified by snapshot as the size of the data disk.
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type DataDisksParameters struct {

	// The ID of the automatic snapshot policy applied to the system disk.
	// +kubebuilder:validation:Optional
	AutoSnapshotPolicyID *string `json:"autoSnapshotPolicyId,omitempty" tf:"auto_snapshot_policy_id,omitempty"`

	// The category of the disk:
	// +kubebuilder:validation:Optional
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Delete this data disk when the instance is destroyed. It only works on cloud, cloud_efficiency, cloud_essd, cloud_ssd disk. If the category of this data disk was ephemeral_ssd, please don't set this param. Default value: true.
	// +kubebuilder:validation:Optional
	DeleteWithInstance *bool `json:"deleteWithInstance,omitempty" tf:"delete_with_instance,omitempty"`

	// The description of the data disk.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The mount point of the data disk.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Encrypted the data in this disk. Default value: false.
	// +kubebuilder:validation:Optional
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// The KMS key ID corresponding to the Nth data disk.
	// +kubebuilder:validation:Optional
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The name of the data disk.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The performance level of the ESSD used as data disk:
	// +kubebuilder:validation:Optional
	PerformanceLevel *string `json:"performanceLevel,omitempty" tf:"performance_level,omitempty"`

	// The size of the data disk.
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size" tf:"size,omitempty"`

	// The snapshot ID used to initialize the data disk. If the size specified by snapshot is greater that the size of the disk, use the size specified by snapshot as the size of the data disk.
	// +kubebuilder:validation:Optional
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type InstanceInitParameters struct {

	// (Deprecated) It has been deprecated from version "1.7.0". Setting "internet_max_bandwidth_out" larger than 0 can allocate a public ip address for an instance.
	AllocatePublicIP *bool `json:"allocatePublicIp,omitempty" tf:"allocate_public_ip,omitempty"`

	// The automatic release time of the PostPaid instance.
	// The time follows the ISO 8601 standard and is in UTC time. Format: yyyy-MM-ddTHH:mm:ssZ. It must be at least half an hour later than the current time and less than 3 years since the current time.
	// Setting it to null can cancel automatic release feature, and the ECS instance will not be released automatically.
	AutoReleaseTime *string `json:"autoReleaseTime,omitempty" tf:"auto_release_time,omitempty"`

	// Auto renewal period of an instance, in the unit of month. It is valid when instance_charge_type is PrePaid. Default to 1. Valid value:
	AutoRenewPeriod *float64 `json:"autoRenewPeriod,omitempty" tf:"auto_renew_period,omitempty"`

	// The Zone to start the instance in. It is ignored and will be computed when set vswitch_id.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Performance mode of the t5 burstable instance. Valid values: 'Standard', 'Unlimited'.
	CreditSpecification *string `json:"creditSpecification,omitempty" tf:"credit_specification,omitempty"`

	// The list of data disks created with instance. See data_disks below.
	DataDisks []DataDisksInitParameters `json:"dataDisks,omitempty" tf:"data_disks,omitempty"`

	// The ID of the dedicated host on which to create the instance. If you set the DedicatedHostId parameter, the spot_strategy and spot_price_limit parameters cannot be set. This is because preemptible instances cannot be created on dedicated hosts.
	DedicatedHostID *string `json:"dedicatedHostId,omitempty" tf:"dedicated_host_id,omitempty"`

	// Whether enable the deletion protection or not. It does not work when the instance is spot. Default value: false.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// The ID of the deployment set to which to deploy the instance. NOTE: From version 1.176.0, instance's deploymentSetId can be removed when 'deployment_set_id' = "".
	DeploymentSetID *string `json:"deploymentSetId,omitempty" tf:"deployment_set_id,omitempty"`

	// Description of the instance, This description can have a string of 2 to 256 characters, It cannot begin with http:// or https://. Default value is null.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether to send a dry-run request. Default to false.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// If it is true, the "PrePaid" instance will be change to "PostPaid" and then deleted forcibly.
	// However, because of changing instance charge type has CPU core count quota limitation, so strongly recommand that "Don't modify instance charge type frequentlly in one month".
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// Specifies whether to enable the access channel for instance metadata. Valid values: enabled, disabled. Default value: enabled.
	HTTPEndpoint *string `json:"httpEndpoint,omitempty" tf:"http_endpoint,omitempty"`

	// The HTTP PUT response hop limit for accessing instance metadata. Valid values: 1 to 64. Default value: 1.
	HTTPPutResponseHopLimit *float64 `json:"httpPutResponseHopLimit,omitempty" tf:"http_put_response_hop_limit,omitempty"`

	// Specifies whether to forcefully use the security-enhanced mode (IMDSv2) to access instance metadata. Default value: optional. Valid values:
	HTTPTokens *string `json:"httpTokens,omitempty" tf:"http_tokens,omitempty"`

	// Host name of the ECS, which is a string of at least two characters. “hostname” cannot start or end with “.” or “-“. In addition, two or more consecutive “.” or “-“ symbols are not allowed. On Windows, the host name can contain a maximum of 15 characters, which can be a combination of uppercase/lowercase letters, numerals, and “-“. The host name cannot contain dots (“.”) or contain only numeric characters. When it is changed, the instance will reboot to make the change take effect.
	// On other OSs such as Linux, the host name can contain a maximum of 64 characters, which can be segments separated by dots (“.”), where each segment can contain uppercase/lowercase letters, numerals, or “_“. When it is changed, the instance will reboot to make the change take effect.
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// The ID of the Elastic High Performance Computing (E-HPC) cluster to which to assign the instance.
	HpcClusterID *string `json:"hpcClusterId,omitempty" tf:"hpc_cluster_id,omitempty"`

	// The number of IPv6 addresses to randomly generate for the primary ENI. Valid values: 1 to 10. NOTE: You cannot specify both the ipv6_addresses and ipv6_address_count parameters.
	IPv6AddressCount *float64 `json:"ipv6AddressCount,omitempty" tf:"ipv6_address_count,omitempty"`

	// A list of IPv6 address to be assigned to the primary ENI. Support up to 10.
	// +listType=set
	IPv6Addresses []*string `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// The Image to use for the instance. ECS instance's image can be replaced via changing image_id. When it is changed, the instance will reboot to make the change take effect. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify image_id.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Whether to change instance disks charge type when changing instance charge type.
	IncludeDataDisks *bool `json:"includeDataDisks,omitempty" tf:"include_data_disks,omitempty"`

	// Valid values are PrePaid, PostPaid, The default is PostPaid.
	// NOTE: Since 1.9.6, it can be changed each other between PostPaid and PrePaid.
	// However, since some limitation about CPU core count in one month,
	// there strongly recommends that Don't change instance_charge_type frequentlly in one month.
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// The name of the ECS. This instance_name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not begin with a hyphen, and must not begin with http:// or https://.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// The type of instance to start. When it is changed, the instance will reboot to make the change take effect. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify instance_type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Internet charge type of the instance, Valid values are PayByBandwidth, PayByTraffic. Default is PayByTraffic. At present, 'PrePaid' instance cannot change the value to "PayByBandwidth" from "PayByTraffic".
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// Maximum incoming bandwidth from the public network, measured in Mbps (Mega bit per second). Value range: [1, 200]. If this value is not specified, then automatically sets it to 200 Mbps.
	InternetMaxBandwidthIn *float64 `json:"internetMaxBandwidthIn,omitempty" tf:"internet_max_bandwidth_in,omitempty"`

	// Maximum outgoing bandwidth to the public network, measured in Mbps (Mega bit per second). Value range:  [0, 100]. Default to 0 Mbps.
	InternetMaxBandwidthOut *float64 `json:"internetMaxBandwidthOut,omitempty" tf:"internet_max_bandwidth_out,omitempty"`

	// (Removed) It has been deprecated on instance resource. All the launched alicloud instances will be I/O optimized.
	IoOptimized *string `json:"ioOptimized,omitempty" tf:"io_optimized,omitempty"`

	// Whether to use outdated instance type. Default to false.
	IsOutdated *bool `json:"isOutdated,omitempty" tf:"is_outdated,omitempty"`

	// An KMS encrypts password used to an instance. If the password is filled in, this field will be ignored. When it is changed, the instance will reboot to make the change take effect.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating an instance with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set. When it is changed, the instance will reboot to make the change take effect.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The name of key pair that can login ECS instance successfully without password. If it is specified, the password would be invalid.
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// The ID of the launch template. For more information, see DescribeLaunchTemplates.To use a launch template to create an instance, you must use the launch_template_id or launch_template_name parameter to specify the launch template.
	LaunchTemplateID *string `json:"launchTemplateId,omitempty" tf:"launch_template_id,omitempty"`

	// The name of the launch template.
	LaunchTemplateName *string `json:"launchTemplateName,omitempty" tf:"launch_template_name,omitempty"`

	// The version of the launch template. If you set launch_template_id or launch_template_name parameter but do not set the version number of the launch template, the default template version is used.
	LaunchTemplateVersion *string `json:"launchTemplateVersion,omitempty" tf:"launch_template_version,omitempty"`

	// The maintenance action. Valid values: Stop, AutoRecover and AutoRedeploy.
	MaintenanceAction *string `json:"maintenanceAction,omitempty" tf:"maintenance_action,omitempty"`

	// Specifies whether to send an event notification before instance shutdown. Valid values: true, false. Default value: false.
	MaintenanceNotify *bool `json:"maintenanceNotify,omitempty" tf:"maintenance_notify,omitempty"`

	// The time of maintenance. See maintenance_time below.
	MaintenanceTime []MaintenanceTimeInitParameters `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	// The list of network interfaces created with instance. See network_interfaces below.
	NetworkInterfaces []NetworkInterfacesInitParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// The operation type. It is valid when instance_charge_type is PrePaid. Default value: upgrade. Valid values: upgrade, downgrade. NOTE:  When the new instance type specified by the instance_type parameter has lower specifications than the current instance type, you must set operator_type to downgrade.
	OperatorType *string `json:"operatorType,omitempty" tf:"operator_type,omitempty"`

	// The duration that you will buy the resource, in month. It is valid when instance_charge_type is PrePaid. Valid values:
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The duration unit that you will buy the resource. It is valid when instance_charge_type is 'PrePaid'. Valid value: ["Week", "Month"]. Default to "Month".
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// Instance private IP address can be specified when you creating new instance. It is valid when vswitch_id is specified. When it is changed, the instance will reboot to make the change take effect.
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// Whether to renew an ECS instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to "Normal". Valid values:
	RenewalStatus *string `json:"renewalStatus,omitempty" tf:"renewal_status,omitempty"`

	// The Id of resource group which the instance belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Instance RAM role name. The name is provided and maintained by RAM. You can use alicloud_ram_role to create a new one.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// The number of private IP addresses to be automatically assigned from within the CIDR block of the vswitch. NOTE: To assign secondary private IP addresses, you must specify secondary_private_ips or secondary_private_ip_address_count but not both.
	SecondaryPrivateIPAddressCount *float64 `json:"secondaryPrivateIpAddressCount,omitempty" tf:"secondary_private_ip_address_count,omitempty"`

	// A list of Secondary private IP addresses which is selected from within the CIDR block of the VSwitch.
	// +listType=set
	SecondaryPrivateIps []*string `json:"secondaryPrivateIps,omitempty" tf:"secondary_private_ips,omitempty"`

	// The security enhancement strategy.
	SecurityEnhancementStrategy *string `json:"securityEnhancementStrategy,omitempty" tf:"security_enhancement_strategy,omitempty"`

	// A list of security group ids to associate with. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify security_groups.
	// +listType=set
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// The retention time of the preemptive instance in hours. Valid values: 0, 1, 2, 3, 4, 5, 6. Retention duration 2~6 is under invitation test, please submit a work order if you need to open. If the value is 0, the mode is no protection period. Default value is 1.
	SpotDuration *float64 `json:"spotDuration,omitempty" tf:"spot_duration,omitempty"`

	// The hourly price threshold of a instance, and it takes effect only when parameter 'spot_strategy' is 'SpotWithPriceLimit'. Three decimals is allowed at most.
	SpotPriceLimit *float64 `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The spot strategy of a Pay-As-You-Go instance, and it takes effect only when parameter instance_charge_type is 'PostPaid'. Value range:
	SpotStrategy *string `json:"spotStrategy,omitempty" tf:"spot_strategy,omitempty"`

	// The instance status. Valid values: ["Running", "Stopped"]. You can control the instance start and stop through this parameter. Default to Running.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The stop mode of the pay-as-you-go instance. Valid values: StopCharging,KeepCharging, Not-applicable. Default value: If the prerequisites required for enabling the economical mode are met, and you have enabled this mode in the ECS console, the default value is StopCharging. For more information, see "Enable the economical mode" in Economical mode. Otherwise, the default value is KeepCharging. Note: Not-applicable: Economical mode is not applicable to the instance.`
	StoppedMode *string `json:"stoppedMode,omitempty" tf:"stopped_mode,omitempty"`

	// The ID of the automatic snapshot policy applied to the system disk.
	SystemDiskAutoSnapshotPolicyID *string `json:"systemDiskAutoSnapshotPolicyId,omitempty" tf:"system_disk_auto_snapshot_policy_id,omitempty"`

	// Valid values are ephemeral_ssd, cloud_efficiency, cloud_ssd, cloud_essd, cloud, cloud_auto, cloud_essd_entry. only is used to some none I/O optimized instance. Default to cloud_efficiency. Valid values cloud_auto Available since 1.184.0+.
	SystemDiskCategory *string `json:"systemDiskCategory,omitempty" tf:"system_disk_category,omitempty"`

	// The description of the system disk. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	SystemDiskDescription *string `json:"systemDiskDescription,omitempty" tf:"system_disk_description,omitempty"`

	// The algorithm to be used to encrypt the system disk. Valid values are aes-256, sm4-128. Default value is aes-256.
	SystemDiskEncryptAlgorithm *string `json:"systemDiskEncryptAlgorithm,omitempty" tf:"system_disk_encrypt_algorithm,omitempty"`

	// Specifies whether to encrypt the system disk. Valid values: true,false. Default value: false.
	SystemDiskEncrypted *bool `json:"systemDiskEncrypted,omitempty" tf:"system_disk_encrypted,omitempty"`

	// The ID of the Key Management Service (KMS) key to be used for the system disk.
	SystemDiskKMSKeyID *string `json:"systemDiskKmsKeyId,omitempty" tf:"system_disk_kms_key_id,omitempty"`

	// The name of the system disk. The name must be 2 to 128 characters in length and can contain letters, digits, periods (.), colons (:), underscores (_), and hyphens (-). It must start with a letter and cannot start with http:// or https://.
	SystemDiskName *string `json:"systemDiskName,omitempty" tf:"system_disk_name,omitempty"`

	// The performance level of the ESSD used as the system disk, Valid values: PL0, PL1, PL2, PL3, Default to PL1;For more information about ESSD, See Encryption Context.
	SystemDiskPerformanceLevel *string `json:"systemDiskPerformanceLevel,omitempty" tf:"system_disk_performance_level,omitempty"`

	// Size of the system disk, measured in GiB. Value range: [20, 500]. The specified value must be equal to or greater than max{20, Imagesize}. Default value: max{40, ImageSize}.
	SystemDiskSize *float64 `json:"systemDiskSize,omitempty" tf:"system_disk_size,omitempty"`

	// The ID of the dedicated block storage cluster. If you want to use disks in a dedicated block storage cluster as system disks when you create instances, you must specify this parameter. For more information about dedicated block storage clusters.
	SystemDiskStorageClusterID *string `json:"systemDiskStorageClusterId,omitempty" tf:"system_disk_storage_cluster_id,omitempty"`

	// A mapping of tags to assign to the resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User-defined data to customize the startup behaviors of an ECS instance and to pass data into an ECS instance.
	// It supports to setting a base64-encoded value, and it is the recommended usage.
	// From version 1.60.0, it can be updated in-place. If updated, the instance will reboot to make the change take effect.
	// Note: Not all changes will take effect, and it depends on cloud-init module type.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// A mapping of tags to assign to the devices created by the instance at launch time.
	// +mapType=granular
	VolumeTags map[string]*string `json:"volumeTags,omitempty" tf:"volume_tags,omitempty"`

	// The virtual switch ID to launch in VPC. This parameter must be set unless you can create classic network instances. When it is changed, the instance will reboot to make the change take effect.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`
}

type InstanceObservation struct {

	// (Deprecated) It has been deprecated from version "1.7.0". Setting "internet_max_bandwidth_out" larger than 0 can allocate a public ip address for an instance.
	AllocatePublicIP *bool `json:"allocatePublicIp,omitempty" tf:"allocate_public_ip,omitempty"`

	// The automatic release time of the PostPaid instance.
	// The time follows the ISO 8601 standard and is in UTC time. Format: yyyy-MM-ddTHH:mm:ssZ. It must be at least half an hour later than the current time and less than 3 years since the current time.
	// Setting it to null can cancel automatic release feature, and the ECS instance will not be released automatically.
	AutoReleaseTime *string `json:"autoReleaseTime,omitempty" tf:"auto_release_time,omitempty"`

	// Auto renewal period of an instance, in the unit of month. It is valid when instance_charge_type is PrePaid. Default to 1. Valid value:
	AutoRenewPeriod *float64 `json:"autoRenewPeriod,omitempty" tf:"auto_renew_period,omitempty"`

	// The Zone to start the instance in. It is ignored and will be computed when set vswitch_id.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// The number of vCPUs.
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// Performance mode of the t5 burstable instance. Valid values: 'Standard', 'Unlimited'.
	CreditSpecification *string `json:"creditSpecification,omitempty" tf:"credit_specification,omitempty"`

	// The list of data disks created with instance. See data_disks below.
	DataDisks []DataDisksObservation `json:"dataDisks,omitempty" tf:"data_disks,omitempty"`

	// The ID of the dedicated host on which to create the instance. If you set the DedicatedHostId parameter, the spot_strategy and spot_price_limit parameters cannot be set. This is because preemptible instances cannot be created on dedicated hosts.
	DedicatedHostID *string `json:"dedicatedHostId,omitempty" tf:"dedicated_host_id,omitempty"`

	// Whether enable the deletion protection or not. It does not work when the instance is spot. Default value: false.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// The group number of the instance in a deployment set when the deployment set is use.
	DeploymentSetGroupNo *string `json:"deploymentSetGroupNo,omitempty" tf:"deployment_set_group_no,omitempty"`

	// The ID of the deployment set to which to deploy the instance. NOTE: From version 1.176.0, instance's deploymentSetId can be removed when 'deployment_set_id' = "".
	DeploymentSetID *string `json:"deploymentSetId,omitempty" tf:"deployment_set_id,omitempty"`

	// Description of the instance, This description can have a string of 2 to 256 characters, It cannot begin with http:// or https://. Default value is null.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether to send a dry-run request. Default to false.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// If it is true, the "PrePaid" instance will be change to "PostPaid" and then deleted forcibly.
	// However, because of changing instance charge type has CPU core count quota limitation, so strongly recommand that "Don't modify instance charge type frequentlly in one month".
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// Specifies whether to enable the access channel for instance metadata. Valid values: enabled, disabled. Default value: enabled.
	HTTPEndpoint *string `json:"httpEndpoint,omitempty" tf:"http_endpoint,omitempty"`

	// The HTTP PUT response hop limit for accessing instance metadata. Valid values: 1 to 64. Default value: 1.
	HTTPPutResponseHopLimit *float64 `json:"httpPutResponseHopLimit,omitempty" tf:"http_put_response_hop_limit,omitempty"`

	// Specifies whether to forcefully use the security-enhanced mode (IMDSv2) to access instance metadata. Default value: optional. Valid values:
	HTTPTokens *string `json:"httpTokens,omitempty" tf:"http_tokens,omitempty"`

	// Host name of the ECS, which is a string of at least two characters. “hostname” cannot start or end with “.” or “-“. In addition, two or more consecutive “.” or “-“ symbols are not allowed. On Windows, the host name can contain a maximum of 15 characters, which can be a combination of uppercase/lowercase letters, numerals, and “-“. The host name cannot contain dots (“.”) or contain only numeric characters. When it is changed, the instance will reboot to make the change take effect.
	// On other OSs such as Linux, the host name can contain a maximum of 64 characters, which can be segments separated by dots (“.”), where each segment can contain uppercase/lowercase letters, numerals, or “_“. When it is changed, the instance will reboot to make the change take effect.
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// The ID of the Elastic High Performance Computing (E-HPC) cluster to which to assign the instance.
	HpcClusterID *string `json:"hpcClusterId,omitempty" tf:"hpc_cluster_id,omitempty"`

	// The instance ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The number of IPv6 addresses to randomly generate for the primary ENI. Valid values: 1 to 10. NOTE: You cannot specify both the ipv6_addresses and ipv6_address_count parameters.
	IPv6AddressCount *float64 `json:"ipv6AddressCount,omitempty" tf:"ipv6_address_count,omitempty"`

	// A list of IPv6 address to be assigned to the primary ENI. Support up to 10.
	// +listType=set
	IPv6Addresses []*string `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// The Image to use for the instance. ECS instance's image can be replaced via changing image_id. When it is changed, the instance will reboot to make the change take effect. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify image_id.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Whether to change instance disks charge type when changing instance charge type.
	IncludeDataDisks *bool `json:"includeDataDisks,omitempty" tf:"include_data_disks,omitempty"`

	// Valid values are PrePaid, PostPaid, The default is PostPaid.
	// NOTE: Since 1.9.6, it can be changed each other between PostPaid and PrePaid.
	// However, since some limitation about CPU core count in one month,
	// there strongly recommends that Don't change instance_charge_type frequentlly in one month.
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// The name of the ECS. This instance_name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not begin with a hyphen, and must not begin with http:// or https://.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// The type of instance to start. When it is changed, the instance will reboot to make the change take effect. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify instance_type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Internet charge type of the instance, Valid values are PayByBandwidth, PayByTraffic. Default is PayByTraffic. At present, 'PrePaid' instance cannot change the value to "PayByBandwidth" from "PayByTraffic".
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// Maximum incoming bandwidth from the public network, measured in Mbps (Mega bit per second). Value range: [1, 200]. If this value is not specified, then automatically sets it to 200 Mbps.
	InternetMaxBandwidthIn *float64 `json:"internetMaxBandwidthIn,omitempty" tf:"internet_max_bandwidth_in,omitempty"`

	// Maximum outgoing bandwidth to the public network, measured in Mbps (Mega bit per second). Value range:  [0, 100]. Default to 0 Mbps.
	InternetMaxBandwidthOut *float64 `json:"internetMaxBandwidthOut,omitempty" tf:"internet_max_bandwidth_out,omitempty"`

	// (Removed) It has been deprecated on instance resource. All the launched alicloud instances will be I/O optimized.
	IoOptimized *string `json:"ioOptimized,omitempty" tf:"io_optimized,omitempty"`

	// Whether to use outdated instance type. Default to false.
	IsOutdated *bool `json:"isOutdated,omitempty" tf:"is_outdated,omitempty"`

	// An KMS encrypts password used to an instance. If the password is filled in, this field will be ignored. When it is changed, the instance will reboot to make the change take effect.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating an instance with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set. When it is changed, the instance will reboot to make the change take effect.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The name of key pair that can login ECS instance successfully without password. If it is specified, the password would be invalid.
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// The ID of the launch template. For more information, see DescribeLaunchTemplates.To use a launch template to create an instance, you must use the launch_template_id or launch_template_name parameter to specify the launch template.
	LaunchTemplateID *string `json:"launchTemplateId,omitempty" tf:"launch_template_id,omitempty"`

	// The name of the launch template.
	LaunchTemplateName *string `json:"launchTemplateName,omitempty" tf:"launch_template_name,omitempty"`

	// The version of the launch template. If you set launch_template_id or launch_template_name parameter but do not set the version number of the launch template, the default template version is used.
	LaunchTemplateVersion *string `json:"launchTemplateVersion,omitempty" tf:"launch_template_version,omitempty"`

	// The maintenance action. Valid values: Stop, AutoRecover and AutoRedeploy.
	MaintenanceAction *string `json:"maintenanceAction,omitempty" tf:"maintenance_action,omitempty"`

	// Specifies whether to send an event notification before instance shutdown. Valid values: true, false. Default value: false.
	MaintenanceNotify *bool `json:"maintenanceNotify,omitempty" tf:"maintenance_notify,omitempty"`

	// The time of maintenance. See maintenance_time below.
	MaintenanceTime []MaintenanceTimeObservation `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	// The memory size of the instance. Unit: MiB.
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// The ID of the ENI.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`

	// The list of network interfaces created with instance. See network_interfaces below.
	NetworkInterfaces []NetworkInterfacesObservation `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// The operation type. It is valid when instance_charge_type is PrePaid. Default value: upgrade. Valid values: upgrade, downgrade. NOTE:  When the new instance type specified by the instance_type parameter has lower specifications than the current instance type, you must set operator_type to downgrade.
	OperatorType *string `json:"operatorType,omitempty" tf:"operator_type,omitempty"`

	// The name of the operating system of the instance.
	OsName *string `json:"osName,omitempty" tf:"os_name,omitempty"`

	// The type of the operating system of the instance.
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// The duration that you will buy the resource, in month. It is valid when instance_charge_type is PrePaid. Valid values:
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The duration unit that you will buy the resource. It is valid when instance_charge_type is 'PrePaid'. Valid value: ["Week", "Month"]. Default to "Month".
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// The primary private IP address of the ENI.
	PrimaryIPAddress *string `json:"primaryIpAddress,omitempty" tf:"primary_ip_address,omitempty"`

	// Instance private IP address can be specified when you creating new instance. It is valid when vswitch_id is specified. When it is changed, the instance will reboot to make the change take effect.
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// The instance public ip.
	PublicIP *string `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// Whether to renew an ECS instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to "Normal". Valid values:
	RenewalStatus *string `json:"renewalStatus,omitempty" tf:"renewal_status,omitempty"`

	// The Id of resource group which the instance belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Instance RAM role name. The name is provided and maintained by RAM. You can use alicloud_ram_role to create a new one.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// The number of private IP addresses to be automatically assigned from within the CIDR block of the vswitch. NOTE: To assign secondary private IP addresses, you must specify secondary_private_ips or secondary_private_ip_address_count but not both.
	SecondaryPrivateIPAddressCount *float64 `json:"secondaryPrivateIpAddressCount,omitempty" tf:"secondary_private_ip_address_count,omitempty"`

	// A list of Secondary private IP addresses which is selected from within the CIDR block of the VSwitch.
	// +listType=set
	SecondaryPrivateIps []*string `json:"secondaryPrivateIps,omitempty" tf:"secondary_private_ips,omitempty"`

	// The security enhancement strategy.
	SecurityEnhancementStrategy *string `json:"securityEnhancementStrategy,omitempty" tf:"security_enhancement_strategy,omitempty"`

	// A list of security group ids to associate with. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify security_groups.
	// +listType=set
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// The retention time of the preemptive instance in hours. Valid values: 0, 1, 2, 3, 4, 5, 6. Retention duration 2~6 is under invitation test, please submit a work order if you need to open. If the value is 0, the mode is no protection period. Default value is 1.
	SpotDuration *float64 `json:"spotDuration,omitempty" tf:"spot_duration,omitempty"`

	// The hourly price threshold of a instance, and it takes effect only when parameter 'spot_strategy' is 'SpotWithPriceLimit'. Three decimals is allowed at most.
	SpotPriceLimit *float64 `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The spot strategy of a Pay-As-You-Go instance, and it takes effect only when parameter instance_charge_type is 'PostPaid'. Value range:
	SpotStrategy *string `json:"spotStrategy,omitempty" tf:"spot_strategy,omitempty"`

	// The instance status. Valid values: ["Running", "Stopped"]. You can control the instance start and stop through this parameter. Default to Running.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The stop mode of the pay-as-you-go instance. Valid values: StopCharging,KeepCharging, Not-applicable. Default value: If the prerequisites required for enabling the economical mode are met, and you have enabled this mode in the ECS console, the default value is StopCharging. For more information, see "Enable the economical mode" in Economical mode. Otherwise, the default value is KeepCharging. Note: Not-applicable: Economical mode is not applicable to the instance.`
	StoppedMode *string `json:"stoppedMode,omitempty" tf:"stopped_mode,omitempty"`

	// The ID of the automatic snapshot policy applied to the system disk.
	SystemDiskAutoSnapshotPolicyID *string `json:"systemDiskAutoSnapshotPolicyId,omitempty" tf:"system_disk_auto_snapshot_policy_id,omitempty"`

	// Valid values are ephemeral_ssd, cloud_efficiency, cloud_ssd, cloud_essd, cloud, cloud_auto, cloud_essd_entry. only is used to some none I/O optimized instance. Default to cloud_efficiency. Valid values cloud_auto Available since 1.184.0+.
	SystemDiskCategory *string `json:"systemDiskCategory,omitempty" tf:"system_disk_category,omitempty"`

	// The description of the system disk. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	SystemDiskDescription *string `json:"systemDiskDescription,omitempty" tf:"system_disk_description,omitempty"`

	// The algorithm to be used to encrypt the system disk. Valid values are aes-256, sm4-128. Default value is aes-256.
	SystemDiskEncryptAlgorithm *string `json:"systemDiskEncryptAlgorithm,omitempty" tf:"system_disk_encrypt_algorithm,omitempty"`

	// Specifies whether to encrypt the system disk. Valid values: true,false. Default value: false.
	SystemDiskEncrypted *bool `json:"systemDiskEncrypted,omitempty" tf:"system_disk_encrypted,omitempty"`

	// (Available since v1.210.0) The ID of system disk.
	SystemDiskID *string `json:"systemDiskId,omitempty" tf:"system_disk_id,omitempty"`

	// The ID of the Key Management Service (KMS) key to be used for the system disk.
	SystemDiskKMSKeyID *string `json:"systemDiskKmsKeyId,omitempty" tf:"system_disk_kms_key_id,omitempty"`

	// The name of the system disk. The name must be 2 to 128 characters in length and can contain letters, digits, periods (.), colons (:), underscores (_), and hyphens (-). It must start with a letter and cannot start with http:// or https://.
	SystemDiskName *string `json:"systemDiskName,omitempty" tf:"system_disk_name,omitempty"`

	// The performance level of the ESSD used as the system disk, Valid values: PL0, PL1, PL2, PL3, Default to PL1;For more information about ESSD, See Encryption Context.
	SystemDiskPerformanceLevel *string `json:"systemDiskPerformanceLevel,omitempty" tf:"system_disk_performance_level,omitempty"`

	// Size of the system disk, measured in GiB. Value range: [20, 500]. The specified value must be equal to or greater than max{20, Imagesize}. Default value: max{40, ImageSize}.
	SystemDiskSize *float64 `json:"systemDiskSize,omitempty" tf:"system_disk_size,omitempty"`

	// The ID of the dedicated block storage cluster. If you want to use disks in a dedicated block storage cluster as system disks when you create instances, you must specify this parameter. For more information about dedicated block storage clusters.
	SystemDiskStorageClusterID *string `json:"systemDiskStorageClusterId,omitempty" tf:"system_disk_storage_cluster_id,omitempty"`

	// A mapping of tags to assign to the resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User-defined data to customize the startup behaviors of an ECS instance and to pass data into an ECS instance.
	// It supports to setting a base64-encoded value, and it is the recommended usage.
	// From version 1.60.0, it can be updated in-place. If updated, the instance will reboot to make the change take effect.
	// Note: Not all changes will take effect, and it depends on cloud-init module type.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// A mapping of tags to assign to the devices created by the instance at launch time.
	// +mapType=granular
	VolumeTags map[string]*string `json:"volumeTags,omitempty" tf:"volume_tags,omitempty"`

	// The virtual switch ID to launch in VPC. This parameter must be set unless you can create classic network instances. When it is changed, the instance will reboot to make the change take effect.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`
}

type InstanceParameters struct {

	// (Deprecated) It has been deprecated from version "1.7.0". Setting "internet_max_bandwidth_out" larger than 0 can allocate a public ip address for an instance.
	// +kubebuilder:validation:Optional
	AllocatePublicIP *bool `json:"allocatePublicIp,omitempty" tf:"allocate_public_ip,omitempty"`

	// The automatic release time of the PostPaid instance.
	// The time follows the ISO 8601 standard and is in UTC time. Format: yyyy-MM-ddTHH:mm:ssZ. It must be at least half an hour later than the current time and less than 3 years since the current time.
	// Setting it to null can cancel automatic release feature, and the ECS instance will not be released automatically.
	// +kubebuilder:validation:Optional
	AutoReleaseTime *string `json:"autoReleaseTime,omitempty" tf:"auto_release_time,omitempty"`

	// Auto renewal period of an instance, in the unit of month. It is valid when instance_charge_type is PrePaid. Default to 1. Valid value:
	// +kubebuilder:validation:Optional
	AutoRenewPeriod *float64 `json:"autoRenewPeriod,omitempty" tf:"auto_renew_period,omitempty"`

	// The Zone to start the instance in. It is ignored and will be computed when set vswitch_id.
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Performance mode of the t5 burstable instance. Valid values: 'Standard', 'Unlimited'.
	// +kubebuilder:validation:Optional
	CreditSpecification *string `json:"creditSpecification,omitempty" tf:"credit_specification,omitempty"`

	// The list of data disks created with instance. See data_disks below.
	// +kubebuilder:validation:Optional
	DataDisks []DataDisksParameters `json:"dataDisks,omitempty" tf:"data_disks,omitempty"`

	// The ID of the dedicated host on which to create the instance. If you set the DedicatedHostId parameter, the spot_strategy and spot_price_limit parameters cannot be set. This is because preemptible instances cannot be created on dedicated hosts.
	// +kubebuilder:validation:Optional
	DedicatedHostID *string `json:"dedicatedHostId,omitempty" tf:"dedicated_host_id,omitempty"`

	// Whether enable the deletion protection or not. It does not work when the instance is spot. Default value: false.
	// +kubebuilder:validation:Optional
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// The ID of the deployment set to which to deploy the instance. NOTE: From version 1.176.0, instance's deploymentSetId can be removed when 'deployment_set_id' = "".
	// +kubebuilder:validation:Optional
	DeploymentSetID *string `json:"deploymentSetId,omitempty" tf:"deployment_set_id,omitempty"`

	// Description of the instance, This description can have a string of 2 to 256 characters, It cannot begin with http:// or https://. Default value is null.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether to send a dry-run request. Default to false.
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// If it is true, the "PrePaid" instance will be change to "PostPaid" and then deleted forcibly.
	// However, because of changing instance charge type has CPU core count quota limitation, so strongly recommand that "Don't modify instance charge type frequentlly in one month".
	// +kubebuilder:validation:Optional
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// Specifies whether to enable the access channel for instance metadata. Valid values: enabled, disabled. Default value: enabled.
	// +kubebuilder:validation:Optional
	HTTPEndpoint *string `json:"httpEndpoint,omitempty" tf:"http_endpoint,omitempty"`

	// The HTTP PUT response hop limit for accessing instance metadata. Valid values: 1 to 64. Default value: 1.
	// +kubebuilder:validation:Optional
	HTTPPutResponseHopLimit *float64 `json:"httpPutResponseHopLimit,omitempty" tf:"http_put_response_hop_limit,omitempty"`

	// Specifies whether to forcefully use the security-enhanced mode (IMDSv2) to access instance metadata. Default value: optional. Valid values:
	// +kubebuilder:validation:Optional
	HTTPTokens *string `json:"httpTokens,omitempty" tf:"http_tokens,omitempty"`

	// Host name of the ECS, which is a string of at least two characters. “hostname” cannot start or end with “.” or “-“. In addition, two or more consecutive “.” or “-“ symbols are not allowed. On Windows, the host name can contain a maximum of 15 characters, which can be a combination of uppercase/lowercase letters, numerals, and “-“. The host name cannot contain dots (“.”) or contain only numeric characters. When it is changed, the instance will reboot to make the change take effect.
	// On other OSs such as Linux, the host name can contain a maximum of 64 characters, which can be segments separated by dots (“.”), where each segment can contain uppercase/lowercase letters, numerals, or “_“. When it is changed, the instance will reboot to make the change take effect.
	// +kubebuilder:validation:Optional
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// The ID of the Elastic High Performance Computing (E-HPC) cluster to which to assign the instance.
	// +kubebuilder:validation:Optional
	HpcClusterID *string `json:"hpcClusterId,omitempty" tf:"hpc_cluster_id,omitempty"`

	// The number of IPv6 addresses to randomly generate for the primary ENI. Valid values: 1 to 10. NOTE: You cannot specify both the ipv6_addresses and ipv6_address_count parameters.
	// +kubebuilder:validation:Optional
	IPv6AddressCount *float64 `json:"ipv6AddressCount,omitempty" tf:"ipv6_address_count,omitempty"`

	// A list of IPv6 address to be assigned to the primary ENI. Support up to 10.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPv6Addresses []*string `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// The Image to use for the instance. ECS instance's image can be replaced via changing image_id. When it is changed, the instance will reboot to make the change take effect. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify image_id.
	// +kubebuilder:validation:Optional
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Whether to change instance disks charge type when changing instance charge type.
	// +kubebuilder:validation:Optional
	IncludeDataDisks *bool `json:"includeDataDisks,omitempty" tf:"include_data_disks,omitempty"`

	// Valid values are PrePaid, PostPaid, The default is PostPaid.
	// NOTE: Since 1.9.6, it can be changed each other between PostPaid and PrePaid.
	// However, since some limitation about CPU core count in one month,
	// there strongly recommends that Don't change instance_charge_type frequentlly in one month.
	// +kubebuilder:validation:Optional
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// The name of the ECS. This instance_name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not begin with a hyphen, and must not begin with http:// or https://.
	// +kubebuilder:validation:Optional
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// The type of instance to start. When it is changed, the instance will reboot to make the change take effect. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify instance_type.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// Internet charge type of the instance, Valid values are PayByBandwidth, PayByTraffic. Default is PayByTraffic. At present, 'PrePaid' instance cannot change the value to "PayByBandwidth" from "PayByTraffic".
	// +kubebuilder:validation:Optional
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// Maximum incoming bandwidth from the public network, measured in Mbps (Mega bit per second). Value range: [1, 200]. If this value is not specified, then automatically sets it to 200 Mbps.
	// +kubebuilder:validation:Optional
	InternetMaxBandwidthIn *float64 `json:"internetMaxBandwidthIn,omitempty" tf:"internet_max_bandwidth_in,omitempty"`

	// Maximum outgoing bandwidth to the public network, measured in Mbps (Mega bit per second). Value range:  [0, 100]. Default to 0 Mbps.
	// +kubebuilder:validation:Optional
	InternetMaxBandwidthOut *float64 `json:"internetMaxBandwidthOut,omitempty" tf:"internet_max_bandwidth_out,omitempty"`

	// (Removed) It has been deprecated on instance resource. All the launched alicloud instances will be I/O optimized.
	// +kubebuilder:validation:Optional
	IoOptimized *string `json:"ioOptimized,omitempty" tf:"io_optimized,omitempty"`

	// Whether to use outdated instance type. Default to false.
	// +kubebuilder:validation:Optional
	IsOutdated *bool `json:"isOutdated,omitempty" tf:"is_outdated,omitempty"`

	// An KMS encrypts password used to an instance. If the password is filled in, this field will be ignored. When it is changed, the instance will reboot to make the change take effect.
	// +kubebuilder:validation:Optional
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating an instance with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set. When it is changed, the instance will reboot to make the change take effect.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The name of key pair that can login ECS instance successfully without password. If it is specified, the password would be invalid.
	// +kubebuilder:validation:Optional
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// The ID of the launch template. For more information, see DescribeLaunchTemplates.To use a launch template to create an instance, you must use the launch_template_id or launch_template_name parameter to specify the launch template.
	// +kubebuilder:validation:Optional
	LaunchTemplateID *string `json:"launchTemplateId,omitempty" tf:"launch_template_id,omitempty"`

	// The name of the launch template.
	// +kubebuilder:validation:Optional
	LaunchTemplateName *string `json:"launchTemplateName,omitempty" tf:"launch_template_name,omitempty"`

	// The version of the launch template. If you set launch_template_id or launch_template_name parameter but do not set the version number of the launch template, the default template version is used.
	// +kubebuilder:validation:Optional
	LaunchTemplateVersion *string `json:"launchTemplateVersion,omitempty" tf:"launch_template_version,omitempty"`

	// The maintenance action. Valid values: Stop, AutoRecover and AutoRedeploy.
	// +kubebuilder:validation:Optional
	MaintenanceAction *string `json:"maintenanceAction,omitempty" tf:"maintenance_action,omitempty"`

	// Specifies whether to send an event notification before instance shutdown. Valid values: true, false. Default value: false.
	// +kubebuilder:validation:Optional
	MaintenanceNotify *bool `json:"maintenanceNotify,omitempty" tf:"maintenance_notify,omitempty"`

	// The time of maintenance. See maintenance_time below.
	// +kubebuilder:validation:Optional
	MaintenanceTime []MaintenanceTimeParameters `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	// The list of network interfaces created with instance. See network_interfaces below.
	// +kubebuilder:validation:Optional
	NetworkInterfaces []NetworkInterfacesParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// The operation type. It is valid when instance_charge_type is PrePaid. Default value: upgrade. Valid values: upgrade, downgrade. NOTE:  When the new instance type specified by the instance_type parameter has lower specifications than the current instance type, you must set operator_type to downgrade.
	// +kubebuilder:validation:Optional
	OperatorType *string `json:"operatorType,omitempty" tf:"operator_type,omitempty"`

	// Password to an instance is a string of 8 to 30 characters. It must contain uppercase/lowercase letters and numerals, but cannot contain special symbols. When it is changed, the instance will reboot to make the change take effect.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The duration that you will buy the resource, in month. It is valid when instance_charge_type is PrePaid. Valid values:
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The duration unit that you will buy the resource. It is valid when instance_charge_type is 'PrePaid'. Valid value: ["Week", "Month"]. Default to "Month".
	// +kubebuilder:validation:Optional
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// Instance private IP address can be specified when you creating new instance. It is valid when vswitch_id is specified. When it is changed, the instance will reboot to make the change take effect.
	// +kubebuilder:validation:Optional
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// Whether to renew an ECS instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to "Normal". Valid values:
	// +kubebuilder:validation:Optional
	RenewalStatus *string `json:"renewalStatus,omitempty" tf:"renewal_status,omitempty"`

	// The Id of resource group which the instance belongs.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Instance RAM role name. The name is provided and maintained by RAM. You can use alicloud_ram_role to create a new one.
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// The number of private IP addresses to be automatically assigned from within the CIDR block of the vswitch. NOTE: To assign secondary private IP addresses, you must specify secondary_private_ips or secondary_private_ip_address_count but not both.
	// +kubebuilder:validation:Optional
	SecondaryPrivateIPAddressCount *float64 `json:"secondaryPrivateIpAddressCount,omitempty" tf:"secondary_private_ip_address_count,omitempty"`

	// A list of Secondary private IP addresses which is selected from within the CIDR block of the VSwitch.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecondaryPrivateIps []*string `json:"secondaryPrivateIps,omitempty" tf:"secondary_private_ips,omitempty"`

	// The security enhancement strategy.
	// +kubebuilder:validation:Optional
	SecurityEnhancementStrategy *string `json:"securityEnhancementStrategy,omitempty" tf:"security_enhancement_strategy,omitempty"`

	// A list of security group ids to associate with. If you do not use launch_template_id or launch_template_name to specify a launch template, you must specify security_groups.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// The retention time of the preemptive instance in hours. Valid values: 0, 1, 2, 3, 4, 5, 6. Retention duration 2~6 is under invitation test, please submit a work order if you need to open. If the value is 0, the mode is no protection period. Default value is 1.
	// +kubebuilder:validation:Optional
	SpotDuration *float64 `json:"spotDuration,omitempty" tf:"spot_duration,omitempty"`

	// The hourly price threshold of a instance, and it takes effect only when parameter 'spot_strategy' is 'SpotWithPriceLimit'. Three decimals is allowed at most.
	// +kubebuilder:validation:Optional
	SpotPriceLimit *float64 `json:"spotPriceLimit,omitempty" tf:"spot_price_limit,omitempty"`

	// The spot strategy of a Pay-As-You-Go instance, and it takes effect only when parameter instance_charge_type is 'PostPaid'. Value range:
	// +kubebuilder:validation:Optional
	SpotStrategy *string `json:"spotStrategy,omitempty" tf:"spot_strategy,omitempty"`

	// The instance status. Valid values: ["Running", "Stopped"]. You can control the instance start and stop through this parameter. Default to Running.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The stop mode of the pay-as-you-go instance. Valid values: StopCharging,KeepCharging, Not-applicable. Default value: If the prerequisites required for enabling the economical mode are met, and you have enabled this mode in the ECS console, the default value is StopCharging. For more information, see "Enable the economical mode" in Economical mode. Otherwise, the default value is KeepCharging. Note: Not-applicable: Economical mode is not applicable to the instance.`
	// +kubebuilder:validation:Optional
	StoppedMode *string `json:"stoppedMode,omitempty" tf:"stopped_mode,omitempty"`

	// The ID of the automatic snapshot policy applied to the system disk.
	// +kubebuilder:validation:Optional
	SystemDiskAutoSnapshotPolicyID *string `json:"systemDiskAutoSnapshotPolicyId,omitempty" tf:"system_disk_auto_snapshot_policy_id,omitempty"`

	// Valid values are ephemeral_ssd, cloud_efficiency, cloud_ssd, cloud_essd, cloud, cloud_auto, cloud_essd_entry. only is used to some none I/O optimized instance. Default to cloud_efficiency. Valid values cloud_auto Available since 1.184.0+.
	// +kubebuilder:validation:Optional
	SystemDiskCategory *string `json:"systemDiskCategory,omitempty" tf:"system_disk_category,omitempty"`

	// The description of the system disk. The description must be 2 to 256 characters in length and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	SystemDiskDescription *string `json:"systemDiskDescription,omitempty" tf:"system_disk_description,omitempty"`

	// The algorithm to be used to encrypt the system disk. Valid values are aes-256, sm4-128. Default value is aes-256.
	// +kubebuilder:validation:Optional
	SystemDiskEncryptAlgorithm *string `json:"systemDiskEncryptAlgorithm,omitempty" tf:"system_disk_encrypt_algorithm,omitempty"`

	// Specifies whether to encrypt the system disk. Valid values: true,false. Default value: false.
	// +kubebuilder:validation:Optional
	SystemDiskEncrypted *bool `json:"systemDiskEncrypted,omitempty" tf:"system_disk_encrypted,omitempty"`

	// The ID of the Key Management Service (KMS) key to be used for the system disk.
	// +kubebuilder:validation:Optional
	SystemDiskKMSKeyID *string `json:"systemDiskKmsKeyId,omitempty" tf:"system_disk_kms_key_id,omitempty"`

	// The name of the system disk. The name must be 2 to 128 characters in length and can contain letters, digits, periods (.), colons (:), underscores (_), and hyphens (-). It must start with a letter and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	SystemDiskName *string `json:"systemDiskName,omitempty" tf:"system_disk_name,omitempty"`

	// The performance level of the ESSD used as the system disk, Valid values: PL0, PL1, PL2, PL3, Default to PL1;For more information about ESSD, See Encryption Context.
	// +kubebuilder:validation:Optional
	SystemDiskPerformanceLevel *string `json:"systemDiskPerformanceLevel,omitempty" tf:"system_disk_performance_level,omitempty"`

	// Size of the system disk, measured in GiB. Value range: [20, 500]. The specified value must be equal to or greater than max{20, Imagesize}. Default value: max{40, ImageSize}.
	// +kubebuilder:validation:Optional
	SystemDiskSize *float64 `json:"systemDiskSize,omitempty" tf:"system_disk_size,omitempty"`

	// The ID of the dedicated block storage cluster. If you want to use disks in a dedicated block storage cluster as system disks when you create instances, you must specify this parameter. For more information about dedicated block storage clusters.
	// +kubebuilder:validation:Optional
	SystemDiskStorageClusterID *string `json:"systemDiskStorageClusterId,omitempty" tf:"system_disk_storage_cluster_id,omitempty"`

	// A mapping of tags to assign to the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User-defined data to customize the startup behaviors of an ECS instance and to pass data into an ECS instance.
	// It supports to setting a base64-encoded value, and it is the recommended usage.
	// From version 1.60.0, it can be updated in-place. If updated, the instance will reboot to make the change take effect.
	// Note: Not all changes will take effect, and it depends on cloud-init module type.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// A mapping of tags to assign to the devices created by the instance at launch time.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	VolumeTags map[string]*string `json:"volumeTags,omitempty" tf:"volume_tags,omitempty"`

	// The virtual switch ID to launch in VPC. This parameter must be set unless you can create classic network instances. When it is changed, the instance will reboot to make the change take effect.
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`
}

type MaintenanceTimeInitParameters struct {

	// The end time of maintenance. The time must be on the hour at exactly 0 minute and 0 second. The start_time and end_time parameters must be specified at the same time. The end_time value must be 1 to 23 hours later than the start_time value. Specify the time in the HH:mm:ss format. The time must be in UTC+8.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The start time of maintenance. The time must be on the hour at exactly 0 minute and 0 second. The start_time and end_time parameters must be specified at the same time. The end_time value must be 1 to 23 hours later than the start_time value. Specify the time in the HH:mm:ss format. The time must be in UTC+8.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type MaintenanceTimeObservation struct {

	// The end time of maintenance. The time must be on the hour at exactly 0 minute and 0 second. The start_time and end_time parameters must be specified at the same time. The end_time value must be 1 to 23 hours later than the start_time value. Specify the time in the HH:mm:ss format. The time must be in UTC+8.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The start time of maintenance. The time must be on the hour at exactly 0 minute and 0 second. The start_time and end_time parameters must be specified at the same time. The end_time value must be 1 to 23 hours later than the start_time value. Specify the time in the HH:mm:ss format. The time must be in UTC+8.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type MaintenanceTimeParameters struct {

	// The end time of maintenance. The time must be on the hour at exactly 0 minute and 0 second. The start_time and end_time parameters must be specified at the same time. The end_time value must be 1 to 23 hours later than the start_time value. Specify the time in the HH:mm:ss format. The time must be in UTC+8.
	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The start time of maintenance. The time must be on the hour at exactly 0 minute and 0 second. The start_time and end_time parameters must be specified at the same time. The end_time value must be 1 to 23 hours later than the start_time value. Specify the time in the HH:mm:ss format. The time must be in UTC+8.
	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type NetworkInterfacesInitParameters struct {

	// The ID of the secondary ENI.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`
}

type NetworkInterfacesObservation struct {

	// The ID of the secondary ENI.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`
}

type NetworkInterfacesParameters struct {

	// The ID of the secondary ENI.
	// +kubebuilder:validation:Optional
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Provides an ECS instance resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InstanceSpec   `json:"spec"`
	Status            InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
