apiVersion: v1
kind: Secret
metadata:
  name: cluster-api-provider-aliyun-aliyun-tf-creds
  namespace: cluster-api-provider-aliyun-system
stringData:
  credentials: |
    {
      "access_key": "",
      "secret_key": "",
    }
type: Opaque
