//go:build !ignore_autogenerated

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"github.com/AliyunContainerService/alibabacloud-provider-for-Cluster-API/api/common"
	"github.com/AliyunContainerService/alibabacloud-provider-for-Cluster-API/api/cs/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AdditionalTags) DeepCopyInto(out *AdditionalTags) {
	{
		in := &in
		*out = make(AdditionalTags, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalTags.
func (in AdditionalTags) DeepCopy() AdditionalTags {
	if in == nil {
		return nil
	}
	out := new(AdditionalTags)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlane) DeepCopyInto(out *AliyunManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlane.
func (in *AliyunManagedControlPlane) DeepCopy() *AliyunManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliyunManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneList) DeepCopyInto(out *AliyunManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AliyunManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneList.
func (in *AliyunManagedControlPlaneList) DeepCopy() *AliyunManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliyunManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpec) DeepCopyInto(out *AliyunManagedControlPlaneSpec) {
	*out = *in
	if in.AdditionalTags != nil {
		in, out := &in.AdditionalTags, &out.AdditionalTags
		*out = make(AdditionalTags, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	in.Network.DeepCopyInto(&out.Network)
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]v1alpha1.AddonsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Logging.DeepCopyInto(&out.Logging)
	out.CNI = in.CNI
	out.EntryptionConfig = in.EntryptionConfig
	out.KubeProxy = in.KubeProxy
	out.EndpointAccess = in.EndpointAccess
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpec.
func (in *AliyunManagedControlPlaneSpec) DeepCopy() *AliyunManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecCNI) DeepCopyInto(out *AliyunManagedControlPlaneSpecCNI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecCNI.
func (in *AliyunManagedControlPlaneSpecCNI) DeepCopy() *AliyunManagedControlPlaneSpecCNI {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecCNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecEncryptionConfig) DeepCopyInto(out *AliyunManagedControlPlaneSpecEncryptionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecEncryptionConfig.
func (in *AliyunManagedControlPlaneSpecEncryptionConfig) DeepCopy() *AliyunManagedControlPlaneSpecEncryptionConfig {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecEncryptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecEndpointAccess) DeepCopyInto(out *AliyunManagedControlPlaneSpecEndpointAccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecEndpointAccess.
func (in *AliyunManagedControlPlaneSpecEndpointAccess) DeepCopy() *AliyunManagedControlPlaneSpecEndpointAccess {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecEndpointAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecKubeProxy) DeepCopyInto(out *AliyunManagedControlPlaneSpecKubeProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecKubeProxy.
func (in *AliyunManagedControlPlaneSpecKubeProxy) DeepCopy() *AliyunManagedControlPlaneSpecKubeProxy {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecKubeProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecLogging) DeepCopyInto(out *AliyunManagedControlPlaneSpecLogging) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecLogging.
func (in *AliyunManagedControlPlaneSpecLogging) DeepCopy() *AliyunManagedControlPlaneSpecLogging {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecNetwork) DeepCopyInto(out *AliyunManagedControlPlaneSpecNetwork) {
	*out = *in
	out.Vpc = in.Vpc
	if in.VSwitches != nil {
		in, out := &in.VSwitches, &out.VSwitches
		*out = make(common.VSwitches, len(*in))
		copy(*out, *in)
	}
	out.SecurityGroup = in.SecurityGroup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecNetwork.
func (in *AliyunManagedControlPlaneSpecNetwork) DeepCopy() *AliyunManagedControlPlaneSpecNetwork {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneSpecSecurityGroup) DeepCopyInto(out *AliyunManagedControlPlaneSpecSecurityGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneSpecSecurityGroup.
func (in *AliyunManagedControlPlaneSpecSecurityGroup) DeepCopy() *AliyunManagedControlPlaneSpecSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneSpecSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneStatus) DeepCopyInto(out *AliyunManagedControlPlaneStatus) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(v1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.NetworkStatus = in.NetworkStatus
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]v1alpha1.AddonsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneStatus.
func (in *AliyunManagedControlPlaneStatus) DeepCopy() *AliyunManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunManagedControlPlaneStatusNetwork) DeepCopyInto(out *AliyunManagedControlPlaneStatusNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunManagedControlPlaneStatusNetwork.
func (in *AliyunManagedControlPlaneStatusNetwork) DeepCopy() *AliyunManagedControlPlaneStatusNetwork {
	if in == nil {
		return nil
	}
	out := new(AliyunManagedControlPlaneStatusNetwork)
	in.DeepCopyInto(out)
	return out
}
