apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AliyunMachinePool
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-aliyun
    app.kubernetes.io/managed-by: kustomize
  name: aliyunmachinepool-sample
spec:
  scalingGroup:
    scalingGroupName: test-wsy
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    vswitchIds:
      - vsw-test
  scalingConfiguration:
    imageId: ubuntu_22_04_x64_20G_alibase_20250722.vhd
    instanceTypes:
      - ecs.c6e.xlarge
    securityGroupIds:
      - sg-abc123
    internetChargeType: PayByTraffic
    internetMaxBandwidthIn: 50
    internetMaxBandwidthOut: 50
    systemDiskCategory: cloud_essd
    systemDiskSize: 50
