//go:build !ignore_autogenerated

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionProtectionConfigInitParameters) DeepCopyInto(out *DeletionProtectionConfigInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionProtectionConfigInitParameters.
func (in *DeletionProtectionConfigInitParameters) DeepCopy() *DeletionProtectionConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeletionProtectionConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionProtectionConfigObservation) DeepCopyInto(out *DeletionProtectionConfigObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnabledTime != nil {
		in, out := &in.EnabledTime, &out.EnabledTime
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionProtectionConfigObservation.
func (in *DeletionProtectionConfigObservation) DeepCopy() *DeletionProtectionConfigObservation {
	if in == nil {
		return nil
	}
	out := new(DeletionProtectionConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionProtectionConfigParameters) DeepCopyInto(out *DeletionProtectionConfigParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionProtectionConfigParameters.
func (in *DeletionProtectionConfigParameters) DeepCopy() *DeletionProtectionConfigParameters {
	if in == nil {
		return nil
	}
	out := new(DeletionProtectionConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckInitParameters) DeepCopyInto(out *HealthCheckInitParameters) {
	*out = *in
	if in.HTTPCheckMethod != nil {
		in, out := &in.HTTPCheckMethod, &out.HTTPCheckMethod
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckConnectPort != nil {
		in, out := &in.HealthCheckConnectPort, &out.HealthCheckConnectPort
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckConnectTimeout != nil {
		in, out := &in.HealthCheckConnectTimeout, &out.HealthCheckConnectTimeout
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckDomain != nil {
		in, out := &in.HealthCheckDomain, &out.HealthCheckDomain
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckEnabled != nil {
		in, out := &in.HealthCheckEnabled, &out.HealthCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HealthCheckHTTPCode != nil {
		in, out := &in.HealthCheckHTTPCode, &out.HealthCheckHTTPCode
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.HealthCheckInterval != nil {
		in, out := &in.HealthCheckInterval, &out.HealthCheckInterval
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckType != nil {
		in, out := &in.HealthCheckType, &out.HealthCheckType
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckURL != nil {
		in, out := &in.HealthCheckURL, &out.HealthCheckURL
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckInitParameters.
func (in *HealthCheckInitParameters) DeepCopy() *HealthCheckInitParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckObservation) DeepCopyInto(out *HealthCheckObservation) {
	*out = *in
	if in.HTTPCheckMethod != nil {
		in, out := &in.HTTPCheckMethod, &out.HTTPCheckMethod
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckConnectPort != nil {
		in, out := &in.HealthCheckConnectPort, &out.HealthCheckConnectPort
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckConnectTimeout != nil {
		in, out := &in.HealthCheckConnectTimeout, &out.HealthCheckConnectTimeout
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckDomain != nil {
		in, out := &in.HealthCheckDomain, &out.HealthCheckDomain
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckEnabled != nil {
		in, out := &in.HealthCheckEnabled, &out.HealthCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HealthCheckHTTPCode != nil {
		in, out := &in.HealthCheckHTTPCode, &out.HealthCheckHTTPCode
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.HealthCheckInterval != nil {
		in, out := &in.HealthCheckInterval, &out.HealthCheckInterval
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckType != nil {
		in, out := &in.HealthCheckType, &out.HealthCheckType
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckURL != nil {
		in, out := &in.HealthCheckURL, &out.HealthCheckURL
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckObservation.
func (in *HealthCheckObservation) DeepCopy() *HealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(HealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckParameters) DeepCopyInto(out *HealthCheckParameters) {
	*out = *in
	if in.HTTPCheckMethod != nil {
		in, out := &in.HTTPCheckMethod, &out.HTTPCheckMethod
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckConnectPort != nil {
		in, out := &in.HealthCheckConnectPort, &out.HealthCheckConnectPort
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckConnectTimeout != nil {
		in, out := &in.HealthCheckConnectTimeout, &out.HealthCheckConnectTimeout
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckDomain != nil {
		in, out := &in.HealthCheckDomain, &out.HealthCheckDomain
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckEnabled != nil {
		in, out := &in.HealthCheckEnabled, &out.HealthCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HealthCheckHTTPCode != nil {
		in, out := &in.HealthCheckHTTPCode, &out.HealthCheckHTTPCode
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.HealthCheckInterval != nil {
		in, out := &in.HealthCheckInterval, &out.HealthCheckInterval
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheckType != nil {
		in, out := &in.HealthCheckType, &out.HealthCheckType
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckURL != nil {
		in, out := &in.HealthCheckURL, &out.HealthCheckURL
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckParameters.
func (in *HealthCheckParameters) DeepCopy() *HealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Listener) DeepCopyInto(out *Listener) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Listener.
func (in *Listener) DeepCopy() *Listener {
	if in == nil {
		return nil
	}
	out := new(Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Listener) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerInitParameters) DeepCopyInto(out *ListenerInitParameters) {
	*out = *in
	if in.AlpnEnabled != nil {
		in, out := &in.AlpnEnabled, &out.AlpnEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CACertificateIds != nil {
		in, out := &in.CACertificateIds, &out.CACertificateIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CAEnabled != nil {
		in, out := &in.CAEnabled, &out.CAEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CertificateIds != nil {
		in, out := &in.CertificateIds, &out.CertificateIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Cps != nil {
		in, out := &in.Cps, &out.Cps
		*out = new(float64)
		**out = **in
	}
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(float64)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ListenerDescription != nil {
		in, out := &in.ListenerDescription, &out.ListenerDescription
		*out = new(string)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.Mss != nil {
		in, out := &in.Mss, &out.Mss
		*out = new(float64)
		**out = **in
	}
	if in.ProxyProtocolEnabled != nil {
		in, out := &in.ProxyProtocolEnabled, &out.ProxyProtocolEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecSensorEnabled != nil {
		in, out := &in.SecSensorEnabled, &out.SecSensorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityPolicyID != nil {
		in, out := &in.SecurityPolicyID, &out.SecurityPolicyID
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupID != nil {
		in, out := &in.ServerGroupID, &out.ServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.StartPort != nil {
		in, out := &in.StartPort, &out.StartPort
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerInitParameters.
func (in *ListenerInitParameters) DeepCopy() *ListenerInitParameters {
	if in == nil {
		return nil
	}
	out := new(ListenerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerList) DeepCopyInto(out *ListenerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Listener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerList.
func (in *ListenerList) DeepCopy() *ListenerList {
	if in == nil {
		return nil
	}
	out := new(ListenerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ListenerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerObservation) DeepCopyInto(out *ListenerObservation) {
	*out = *in
	if in.AlpnEnabled != nil {
		in, out := &in.AlpnEnabled, &out.AlpnEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CACertificateIds != nil {
		in, out := &in.CACertificateIds, &out.CACertificateIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CAEnabled != nil {
		in, out := &in.CAEnabled, &out.CAEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CertificateIds != nil {
		in, out := &in.CertificateIds, &out.CertificateIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Cps != nil {
		in, out := &in.Cps, &out.Cps
		*out = new(float64)
		**out = **in
	}
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ListenerDescription != nil {
		in, out := &in.ListenerDescription, &out.ListenerDescription
		*out = new(string)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.Mss != nil {
		in, out := &in.Mss, &out.Mss
		*out = new(float64)
		**out = **in
	}
	if in.ProxyProtocolEnabled != nil {
		in, out := &in.ProxyProtocolEnabled, &out.ProxyProtocolEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecSensorEnabled != nil {
		in, out := &in.SecSensorEnabled, &out.SecSensorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityPolicyID != nil {
		in, out := &in.SecurityPolicyID, &out.SecurityPolicyID
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupID != nil {
		in, out := &in.ServerGroupID, &out.ServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.StartPort != nil {
		in, out := &in.StartPort, &out.StartPort
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerObservation.
func (in *ListenerObservation) DeepCopy() *ListenerObservation {
	if in == nil {
		return nil
	}
	out := new(ListenerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerParameters) DeepCopyInto(out *ListenerParameters) {
	*out = *in
	if in.AlpnEnabled != nil {
		in, out := &in.AlpnEnabled, &out.AlpnEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CACertificateIds != nil {
		in, out := &in.CACertificateIds, &out.CACertificateIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CAEnabled != nil {
		in, out := &in.CAEnabled, &out.CAEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CertificateIds != nil {
		in, out := &in.CertificateIds, &out.CertificateIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Cps != nil {
		in, out := &in.Cps, &out.Cps
		*out = new(float64)
		**out = **in
	}
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(float64)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ListenerDescription != nil {
		in, out := &in.ListenerDescription, &out.ListenerDescription
		*out = new(string)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.Mss != nil {
		in, out := &in.Mss, &out.Mss
		*out = new(float64)
		**out = **in
	}
	if in.ProxyProtocolEnabled != nil {
		in, out := &in.ProxyProtocolEnabled, &out.ProxyProtocolEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecSensorEnabled != nil {
		in, out := &in.SecSensorEnabled, &out.SecSensorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityPolicyID != nil {
		in, out := &in.SecurityPolicyID, &out.SecurityPolicyID
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupID != nil {
		in, out := &in.ServerGroupID, &out.ServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.StartPort != nil {
		in, out := &in.StartPort, &out.StartPort
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerParameters.
func (in *ListenerParameters) DeepCopy() *ListenerParameters {
	if in == nil {
		return nil
	}
	out := new(ListenerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerSpec) DeepCopyInto(out *ListenerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerSpec.
func (in *ListenerSpec) DeepCopy() *ListenerSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerStatus) DeepCopyInto(out *ListenerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerStatus.
func (in *ListenerStatus) DeepCopy() *ListenerStatus {
	if in == nil {
		return nil
	}
	out := new(ListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerInitParameters) DeepCopyInto(out *LoadBalancerInitParameters) {
	*out = *in
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.AddressType != nil {
		in, out := &in.AddressType, &out.AddressType
		*out = new(string)
		**out = **in
	}
	if in.BandwidthPackageID != nil {
		in, out := &in.BandwidthPackageID, &out.BandwidthPackageID
		*out = new(string)
		**out = **in
	}
	if in.CrossZoneEnabled != nil {
		in, out := &in.CrossZoneEnabled, &out.CrossZoneEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeletionProtectionConfig != nil {
		in, out := &in.DeletionProtectionConfig, &out.DeletionProtectionConfig
		*out = make([]DeletionProtectionConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeletionProtectionEnabled != nil {
		in, out := &in.DeletionProtectionEnabled, &out.DeletionProtectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeletionProtectionReason != nil {
		in, out := &in.DeletionProtectionReason, &out.DeletionProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.IPv6AddressType != nil {
		in, out := &in.IPv6AddressType, &out.IPv6AddressType
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerType != nil {
		in, out := &in.LoadBalancerType, &out.LoadBalancerType
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionConfig != nil {
		in, out := &in.ModificationProtectionConfig, &out.ModificationProtectionConfig
		*out = make([]ModificationProtectionConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModificationProtectionReason != nil {
		in, out := &in.ModificationProtectionReason, &out.ModificationProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionStatus != nil {
		in, out := &in.ModificationProtectionStatus, &out.ModificationProtectionStatus
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroupIds != nil {
		in, out := &in.SecurityGroupIds, &out.SecurityGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.ZoneMappings != nil {
		in, out := &in.ZoneMappings, &out.ZoneMappings
		*out = make([]ZoneMappingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerInitParameters.
func (in *LoadBalancerInitParameters) DeepCopy() *LoadBalancerInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerObservation) DeepCopyInto(out *LoadBalancerObservation) {
	*out = *in
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.AddressType != nil {
		in, out := &in.AddressType, &out.AddressType
		*out = new(string)
		**out = **in
	}
	if in.BandwidthPackageID != nil {
		in, out := &in.BandwidthPackageID, &out.BandwidthPackageID
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.CrossZoneEnabled != nil {
		in, out := &in.CrossZoneEnabled, &out.CrossZoneEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.DeletionProtectionConfig != nil {
		in, out := &in.DeletionProtectionConfig, &out.DeletionProtectionConfig
		*out = make([]DeletionProtectionConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeletionProtectionEnabled != nil {
		in, out := &in.DeletionProtectionEnabled, &out.DeletionProtectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeletionProtectionReason != nil {
		in, out := &in.DeletionProtectionReason, &out.DeletionProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPv6AddressType != nil {
		in, out := &in.IPv6AddressType, &out.IPv6AddressType
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerBusinessStatus != nil {
		in, out := &in.LoadBalancerBusinessStatus, &out.LoadBalancerBusinessStatus
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerType != nil {
		in, out := &in.LoadBalancerType, &out.LoadBalancerType
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionConfig != nil {
		in, out := &in.ModificationProtectionConfig, &out.ModificationProtectionConfig
		*out = make([]ModificationProtectionConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModificationProtectionReason != nil {
		in, out := &in.ModificationProtectionReason, &out.ModificationProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionStatus != nil {
		in, out := &in.ModificationProtectionStatus, &out.ModificationProtectionStatus
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroupIds != nil {
		in, out := &in.SecurityGroupIds, &out.SecurityGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.ZoneMappings != nil {
		in, out := &in.ZoneMappings, &out.ZoneMappings
		*out = make([]ZoneMappingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerObservation.
func (in *LoadBalancerObservation) DeepCopy() *LoadBalancerObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerParameters) DeepCopyInto(out *LoadBalancerParameters) {
	*out = *in
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.AddressType != nil {
		in, out := &in.AddressType, &out.AddressType
		*out = new(string)
		**out = **in
	}
	if in.BandwidthPackageID != nil {
		in, out := &in.BandwidthPackageID, &out.BandwidthPackageID
		*out = new(string)
		**out = **in
	}
	if in.CrossZoneEnabled != nil {
		in, out := &in.CrossZoneEnabled, &out.CrossZoneEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeletionProtectionConfig != nil {
		in, out := &in.DeletionProtectionConfig, &out.DeletionProtectionConfig
		*out = make([]DeletionProtectionConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeletionProtectionEnabled != nil {
		in, out := &in.DeletionProtectionEnabled, &out.DeletionProtectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeletionProtectionReason != nil {
		in, out := &in.DeletionProtectionReason, &out.DeletionProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.IPv6AddressType != nil {
		in, out := &in.IPv6AddressType, &out.IPv6AddressType
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerType != nil {
		in, out := &in.LoadBalancerType, &out.LoadBalancerType
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionConfig != nil {
		in, out := &in.ModificationProtectionConfig, &out.ModificationProtectionConfig
		*out = make([]ModificationProtectionConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModificationProtectionReason != nil {
		in, out := &in.ModificationProtectionReason, &out.ModificationProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionStatus != nil {
		in, out := &in.ModificationProtectionStatus, &out.ModificationProtectionStatus
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroupIds != nil {
		in, out := &in.SecurityGroupIds, &out.SecurityGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.ZoneMappings != nil {
		in, out := &in.ZoneMappings, &out.ZoneMappings
		*out = make([]ZoneMappingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerParameters.
func (in *LoadBalancerParameters) DeepCopy() *LoadBalancerParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModificationProtectionConfigInitParameters) DeepCopyInto(out *ModificationProtectionConfigInitParameters) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModificationProtectionConfigInitParameters.
func (in *ModificationProtectionConfigInitParameters) DeepCopy() *ModificationProtectionConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModificationProtectionConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModificationProtectionConfigObservation) DeepCopyInto(out *ModificationProtectionConfigObservation) {
	*out = *in
	if in.EnabledTime != nil {
		in, out := &in.EnabledTime, &out.EnabledTime
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModificationProtectionConfigObservation.
func (in *ModificationProtectionConfigObservation) DeepCopy() *ModificationProtectionConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ModificationProtectionConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModificationProtectionConfigParameters) DeepCopyInto(out *ModificationProtectionConfigParameters) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModificationProtectionConfigParameters.
func (in *ModificationProtectionConfigParameters) DeepCopy() *ModificationProtectionConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ModificationProtectionConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroup) DeepCopyInto(out *ServerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroup.
func (in *ServerGroup) DeepCopy() *ServerGroup {
	if in == nil {
		return nil
	}
	out := new(ServerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroupInitParameters) DeepCopyInto(out *ServerGroupInitParameters) {
	*out = *in
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.AnyPortEnabled != nil {
		in, out := &in.AnyPortEnabled, &out.AnyPortEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrain != nil {
		in, out := &in.ConnectionDrain, &out.ConnectionDrain
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrainEnabled != nil {
		in, out := &in.ConnectionDrainEnabled, &out.ConnectionDrainEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrainTimeout != nil {
		in, out := &in.ConnectionDrainTimeout, &out.ConnectionDrainTimeout
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreserveClientIPEnabled != nil {
		in, out := &in.PreserveClientIPEnabled, &out.PreserveClientIPEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupName != nil {
		in, out := &in.ServerGroupName, &out.ServerGroupName
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupType != nil {
		in, out := &in.ServerGroupType, &out.ServerGroupType
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroupInitParameters.
func (in *ServerGroupInitParameters) DeepCopy() *ServerGroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServerGroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroupList) DeepCopyInto(out *ServerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroupList.
func (in *ServerGroupList) DeepCopy() *ServerGroupList {
	if in == nil {
		return nil
	}
	out := new(ServerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroupObservation) DeepCopyInto(out *ServerGroupObservation) {
	*out = *in
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.AnyPortEnabled != nil {
		in, out := &in.AnyPortEnabled, &out.AnyPortEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrain != nil {
		in, out := &in.ConnectionDrain, &out.ConnectionDrain
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrainEnabled != nil {
		in, out := &in.ConnectionDrainEnabled, &out.ConnectionDrainEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrainTimeout != nil {
		in, out := &in.ConnectionDrainTimeout, &out.ConnectionDrainTimeout
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PreserveClientIPEnabled != nil {
		in, out := &in.PreserveClientIPEnabled, &out.PreserveClientIPEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupName != nil {
		in, out := &in.ServerGroupName, &out.ServerGroupName
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupType != nil {
		in, out := &in.ServerGroupType, &out.ServerGroupType
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroupObservation.
func (in *ServerGroupObservation) DeepCopy() *ServerGroupObservation {
	if in == nil {
		return nil
	}
	out := new(ServerGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroupParameters) DeepCopyInto(out *ServerGroupParameters) {
	*out = *in
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.AnyPortEnabled != nil {
		in, out := &in.AnyPortEnabled, &out.AnyPortEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrain != nil {
		in, out := &in.ConnectionDrain, &out.ConnectionDrain
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrainEnabled != nil {
		in, out := &in.ConnectionDrainEnabled, &out.ConnectionDrainEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDrainTimeout != nil {
		in, out := &in.ConnectionDrainTimeout, &out.ConnectionDrainTimeout
		*out = new(float64)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreserveClientIPEnabled != nil {
		in, out := &in.PreserveClientIPEnabled, &out.PreserveClientIPEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupName != nil {
		in, out := &in.ServerGroupName, &out.ServerGroupName
		*out = new(string)
		**out = **in
	}
	if in.ServerGroupType != nil {
		in, out := &in.ServerGroupType, &out.ServerGroupType
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroupParameters.
func (in *ServerGroupParameters) DeepCopy() *ServerGroupParameters {
	if in == nil {
		return nil
	}
	out := new(ServerGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroupSpec) DeepCopyInto(out *ServerGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroupSpec.
func (in *ServerGroupSpec) DeepCopy() *ServerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ServerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerGroupStatus) DeepCopyInto(out *ServerGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerGroupStatus.
func (in *ServerGroupStatus) DeepCopy() *ServerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ServerGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneMappingsInitParameters) DeepCopyInto(out *ZoneMappingsInitParameters) {
	*out = *in
	if in.AllocationID != nil {
		in, out := &in.AllocationID, &out.AllocationID
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPv4Address != nil {
		in, out := &in.PrivateIPv4Address, &out.PrivateIPv4Address
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.VswitchID != nil {
		in, out := &in.VswitchID, &out.VswitchID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneMappingsInitParameters.
func (in *ZoneMappingsInitParameters) DeepCopy() *ZoneMappingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ZoneMappingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneMappingsObservation) DeepCopyInto(out *ZoneMappingsObservation) {
	*out = *in
	if in.AllocationID != nil {
		in, out := &in.AllocationID, &out.AllocationID
		*out = new(string)
		**out = **in
	}
	if in.EniID != nil {
		in, out := &in.EniID, &out.EniID
		*out = new(string)
		**out = **in
	}
	if in.IPv6Address != nil {
		in, out := &in.IPv6Address, &out.IPv6Address
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPv4Address != nil {
		in, out := &in.PrivateIPv4Address, &out.PrivateIPv4Address
		*out = new(string)
		**out = **in
	}
	if in.PublicIPv4Address != nil {
		in, out := &in.PublicIPv4Address, &out.PublicIPv4Address
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.VswitchID != nil {
		in, out := &in.VswitchID, &out.VswitchID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneMappingsObservation.
func (in *ZoneMappingsObservation) DeepCopy() *ZoneMappingsObservation {
	if in == nil {
		return nil
	}
	out := new(ZoneMappingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneMappingsParameters) DeepCopyInto(out *ZoneMappingsParameters) {
	*out = *in
	if in.AllocationID != nil {
		in, out := &in.AllocationID, &out.AllocationID
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPv4Address != nil {
		in, out := &in.PrivateIPv4Address, &out.PrivateIPv4Address
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.VswitchID != nil {
		in, out := &in.VswitchID, &out.VswitchID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneMappingsParameters.
func (in *ZoneMappingsParameters) DeepCopy() *ZoneMappingsParameters {
	if in == nil {
		return nil
	}
	out := new(ZoneMappingsParameters)
	in.DeepCopyInto(out)
	return out
}
