// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DeletionProtectionConfigInitParameters struct {

	// Delete protection enable.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Reason for opening.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`
}

type DeletionProtectionConfigObservation struct {

	// Delete protection enable.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Opening time.
	EnabledTime *string `json:"enabledTime,omitempty" tf:"enabled_time,omitempty"`

	// Reason for opening.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`
}

type DeletionProtectionConfigParameters struct {

	// Delete protection enable.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Reason for opening.
	// +kubebuilder:validation:Optional
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`
}

type LoadBalancerInitParameters struct {

	// Protocol version. Value:
	AddressIPVersion *string `json:"addressIpVersion,omitempty" tf:"address_ip_version,omitempty"`

	// The network address type of IPv4 for network load balancing. Value:
	AddressType *string `json:"addressType,omitempty" tf:"address_type,omitempty"`

	// The ID of the shared bandwidth package associated with the public network instance.
	BandwidthPackageID *string `json:"bandwidthPackageId,omitempty" tf:"bandwidth_package_id,omitempty"`

	// Whether cross-zone is enabled for a network-based load balancing instance. Value:
	CrossZoneEnabled *bool `json:"crossZoneEnabled,omitempty" tf:"cross_zone_enabled,omitempty"`

	// Delete protection. See deletion_protection_config below.
	DeletionProtectionConfig []DeletionProtectionConfigInitParameters `json:"deletionProtectionConfig,omitempty" tf:"deletion_protection_config,omitempty"`

	// Specifies whether to enable deletion protection. Default value: false. Valid values:
	DeletionProtectionEnabled *bool `json:"deletionProtectionEnabled,omitempty" tf:"deletion_protection_enabled,omitempty"`

	// The reason why the deletion protection feature is enabled or disabled. The deletion_protection_reason takes effect only when deletion_protection_enabled is set to true.
	DeletionProtectionReason *string `json:"deletionProtectionReason,omitempty" tf:"deletion_protection_reason,omitempty"`

	// The IPv6 address type of network load balancing. Value:
	IPv6AddressType *string `json:"ipv6AddressType,omitempty" tf:"ipv6_address_type,omitempty"`

	// The name of the network-based load balancing instance.  2 to 128 English or Chinese characters in length, which must start with a letter or Chinese, and can contain numbers, half-width periods (.), underscores (_), and dashes (-).
	LoadBalancerName *string `json:"loadBalancerName,omitempty" tf:"load_balancer_name,omitempty"`

	// Load balancing type. Only value: network, which indicates network-based load balancing.
	LoadBalancerType *string `json:"loadBalancerType,omitempty" tf:"load_balancer_type,omitempty"`

	// Modify protection. See modification_protection_config below.
	ModificationProtectionConfig []ModificationProtectionConfigInitParameters `json:"modificationProtectionConfig,omitempty" tf:"modification_protection_config,omitempty"`

	// The reason why the configuration read-only mode is enabled. The modification_protection_reason takes effect only when modification_protection_status is set to ConsoleProtection.
	ModificationProtectionReason *string `json:"modificationProtectionReason,omitempty" tf:"modification_protection_reason,omitempty"`

	// Specifies whether to enable the configuration read-only mode. Default value: NonProtection. Valid values:
	ModificationProtectionStatus *string `json:"modificationProtectionStatus,omitempty" tf:"modification_protection_status,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The security group to which the network-based SLB instance belongs.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// List of labels.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the network-based SLB instance.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// The list of zones and vSwitch mappings. You must add at least two zones and a maximum of 10 zones. See zone_mappings below.
	ZoneMappings []ZoneMappingsInitParameters `json:"zoneMappings,omitempty" tf:"zone_mappings,omitempty"`
}

type LoadBalancerObservation struct {

	// Protocol version. Value:
	AddressIPVersion *string `json:"addressIpVersion,omitempty" tf:"address_ip_version,omitempty"`

	// The network address type of IPv4 for network load balancing. Value:
	AddressType *string `json:"addressType,omitempty" tf:"address_type,omitempty"`

	// The ID of the shared bandwidth package associated with the public network instance.
	BandwidthPackageID *string `json:"bandwidthPackageId,omitempty" tf:"bandwidth_package_id,omitempty"`

	// Resource creation time, using Greenwich Mean Time, formating' yyyy-MM-ddTHH:mm:ssZ '.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Whether cross-zone is enabled for a network-based load balancing instance. Value:
	CrossZoneEnabled *bool `json:"crossZoneEnabled,omitempty" tf:"cross_zone_enabled,omitempty"`

	// The domain name of the NLB instance.
	DNSName *string `json:"dnsName,omitempty" tf:"dns_name,omitempty"`

	// Delete protection. See deletion_protection_config below.
	DeletionProtectionConfig []DeletionProtectionConfigObservation `json:"deletionProtectionConfig,omitempty" tf:"deletion_protection_config,omitempty"`

	// Specifies whether to enable deletion protection. Default value: false. Valid values:
	DeletionProtectionEnabled *bool `json:"deletionProtectionEnabled,omitempty" tf:"deletion_protection_enabled,omitempty"`

	// The reason why the deletion protection feature is enabled or disabled. The deletion_protection_reason takes effect only when deletion_protection_enabled is set to true.
	DeletionProtectionReason *string `json:"deletionProtectionReason,omitempty" tf:"deletion_protection_reason,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The IPv6 address type of network load balancing. Value:
	IPv6AddressType *string `json:"ipv6AddressType,omitempty" tf:"ipv6_address_type,omitempty"`

	// The business status of the NLB instance.
	LoadBalancerBusinessStatus *string `json:"loadBalancerBusinessStatus,omitempty" tf:"load_balancer_business_status,omitempty"`

	// The name of the network-based load balancing instance.  2 to 128 English or Chinese characters in length, which must start with a letter or Chinese, and can contain numbers, half-width periods (.), underscores (_), and dashes (-).
	LoadBalancerName *string `json:"loadBalancerName,omitempty" tf:"load_balancer_name,omitempty"`

	// Load balancing type. Only value: network, which indicates network-based load balancing.
	LoadBalancerType *string `json:"loadBalancerType,omitempty" tf:"load_balancer_type,omitempty"`

	// Modify protection. See modification_protection_config below.
	ModificationProtectionConfig []ModificationProtectionConfigObservation `json:"modificationProtectionConfig,omitempty" tf:"modification_protection_config,omitempty"`

	// The reason why the configuration read-only mode is enabled. The modification_protection_reason takes effect only when modification_protection_status is set to ConsoleProtection.
	ModificationProtectionReason *string `json:"modificationProtectionReason,omitempty" tf:"modification_protection_reason,omitempty"`

	// Specifies whether to enable the configuration read-only mode. Default value: NonProtection. Valid values:
	ModificationProtectionStatus *string `json:"modificationProtectionStatus,omitempty" tf:"modification_protection_status,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The security group to which the network-based SLB instance belongs.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// The status of the resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// List of labels.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the network-based SLB instance.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// The list of zones and vSwitch mappings. You must add at least two zones and a maximum of 10 zones. See zone_mappings below.
	ZoneMappings []ZoneMappingsObservation `json:"zoneMappings,omitempty" tf:"zone_mappings,omitempty"`
}

type LoadBalancerParameters struct {

	// Protocol version. Value:
	// +kubebuilder:validation:Optional
	AddressIPVersion *string `json:"addressIpVersion,omitempty" tf:"address_ip_version,omitempty"`

	// The network address type of IPv4 for network load balancing. Value:
	// +kubebuilder:validation:Optional
	AddressType *string `json:"addressType,omitempty" tf:"address_type,omitempty"`

	// The ID of the shared bandwidth package associated with the public network instance.
	// +kubebuilder:validation:Optional
	BandwidthPackageID *string `json:"bandwidthPackageId,omitempty" tf:"bandwidth_package_id,omitempty"`

	// Whether cross-zone is enabled for a network-based load balancing instance. Value:
	// +kubebuilder:validation:Optional
	CrossZoneEnabled *bool `json:"crossZoneEnabled,omitempty" tf:"cross_zone_enabled,omitempty"`

	// Delete protection. See deletion_protection_config below.
	// +kubebuilder:validation:Optional
	DeletionProtectionConfig []DeletionProtectionConfigParameters `json:"deletionProtectionConfig,omitempty" tf:"deletion_protection_config,omitempty"`

	// Specifies whether to enable deletion protection. Default value: false. Valid values:
	// +kubebuilder:validation:Optional
	DeletionProtectionEnabled *bool `json:"deletionProtectionEnabled,omitempty" tf:"deletion_protection_enabled,omitempty"`

	// The reason why the deletion protection feature is enabled or disabled. The deletion_protection_reason takes effect only when deletion_protection_enabled is set to true.
	// +kubebuilder:validation:Optional
	DeletionProtectionReason *string `json:"deletionProtectionReason,omitempty" tf:"deletion_protection_reason,omitempty"`

	// The IPv6 address type of network load balancing. Value:
	// +kubebuilder:validation:Optional
	IPv6AddressType *string `json:"ipv6AddressType,omitempty" tf:"ipv6_address_type,omitempty"`

	// The name of the network-based load balancing instance.  2 to 128 English or Chinese characters in length, which must start with a letter or Chinese, and can contain numbers, half-width periods (.), underscores (_), and dashes (-).
	// +kubebuilder:validation:Optional
	LoadBalancerName *string `json:"loadBalancerName,omitempty" tf:"load_balancer_name,omitempty"`

	// Load balancing type. Only value: network, which indicates network-based load balancing.
	// +kubebuilder:validation:Optional
	LoadBalancerType *string `json:"loadBalancerType,omitempty" tf:"load_balancer_type,omitempty"`

	// Modify protection. See modification_protection_config below.
	// +kubebuilder:validation:Optional
	ModificationProtectionConfig []ModificationProtectionConfigParameters `json:"modificationProtectionConfig,omitempty" tf:"modification_protection_config,omitempty"`

	// The reason why the configuration read-only mode is enabled. The modification_protection_reason takes effect only when modification_protection_status is set to ConsoleProtection.
	// +kubebuilder:validation:Optional
	ModificationProtectionReason *string `json:"modificationProtectionReason,omitempty" tf:"modification_protection_reason,omitempty"`

	// Specifies whether to enable the configuration read-only mode. Default value: NonProtection. Valid values:
	// +kubebuilder:validation:Optional
	ModificationProtectionStatus *string `json:"modificationProtectionStatus,omitempty" tf:"modification_protection_status,omitempty"`

	// The ID of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The security group to which the network-based SLB instance belongs.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// List of labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the network-based SLB instance.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// The list of zones and vSwitch mappings. You must add at least two zones and a maximum of 10 zones. See zone_mappings below.
	// +kubebuilder:validation:Optional
	ZoneMappings []ZoneMappingsParameters `json:"zoneMappings,omitempty" tf:"zone_mappings,omitempty"`
}

type ModificationProtectionConfigInitParameters struct {

	// Reason for opening.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	// ON.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ModificationProtectionConfigObservation struct {

	// Opening time.
	EnabledTime *string `json:"enabledTime,omitempty" tf:"enabled_time,omitempty"`

	// Reason for opening.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	// ON.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ModificationProtectionConfigParameters struct {

	// Reason for opening.
	// +kubebuilder:validation:Optional
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	// ON.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ZoneMappingsInitParameters struct {

	// The ID of the elastic IP address.
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	// The private IPv4 address of a network-based server load balancer instance.
	PrivateIPv4Address *string `json:"privateIpv4Address,omitempty" tf:"private_ipv4_address,omitempty"`

	// Zone Status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The switch corresponding to the zone. Each zone uses one switch and one subnet by default.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// The name of the zone. You can call the [DescribeZones](~~ 443890 ~~) operation to obtain the name of the zone.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ZoneMappingsObservation struct {

	// The ID of the elastic IP address.
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	// The ID of ENI.
	EniID *string `json:"eniId,omitempty" tf:"eni_id,omitempty"`

	// The IPv6 address of a network-based server load balancer instance.
	IPv6Address *string `json:"ipv6Address,omitempty" tf:"ipv6_address,omitempty"`

	// The private IPv4 address of a network-based server load balancer instance.
	PrivateIPv4Address *string `json:"privateIpv4Address,omitempty" tf:"private_ipv4_address,omitempty"`

	// Public IPv4 address of a network-based server load balancer instance.
	PublicIPv4Address *string `json:"publicIpv4Address,omitempty" tf:"public_ipv4_address,omitempty"`

	// Zone Status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The switch corresponding to the zone. Each zone uses one switch and one subnet by default.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// The name of the zone. You can call the [DescribeZones](~~ 443890 ~~) operation to obtain the name of the zone.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ZoneMappingsParameters struct {

	// The ID of the elastic IP address.
	// +kubebuilder:validation:Optional
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	// The private IPv4 address of a network-based server load balancer instance.
	// +kubebuilder:validation:Optional
	PrivateIPv4Address *string `json:"privateIpv4Address,omitempty" tf:"private_ipv4_address,omitempty"`

	// Zone Status.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The switch corresponding to the zone. Each zone uses one switch and one subnet by default.
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId" tf:"vswitch_id,omitempty"`

	// The name of the zone. You can call the [DescribeZones](~~ 443890 ~~) operation to obtain the name of the zone.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId" tf:"zone_id,omitempty"`
}

// LoadBalancerSpec defines the desired state of LoadBalancer
type LoadBalancerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LoadBalancerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerStatus defines the observed state of LoadBalancer.
type LoadBalancerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancer is the Schema for the LoadBalancers API. Provides a Alicloud NLB Load Balancer resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type LoadBalancer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.addressType) || (has(self.initProvider) && has(self.initProvider.addressType))",message="spec.forProvider.addressType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcId) || (has(self.initProvider) && has(self.initProvider.vpcId))",message="spec.forProvider.vpcId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneMappings) || (has(self.initProvider) && has(self.initProvider.zoneMappings))",message="spec.forProvider.zoneMappings is a required parameter"
	Spec   LoadBalancerSpec   `json:"spec"`
	Status LoadBalancerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerList contains a list of LoadBalancers
type LoadBalancerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancer `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancer_Kind             = "LoadBalancer"
	LoadBalancer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancer_Kind}.String()
	LoadBalancer_KindAPIVersion   = LoadBalancer_Kind + "." + CRDGroupVersion.String()
	LoadBalancer_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancer_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancer{}, &LoadBalancerList{})
}
