// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ListenerInitParameters struct {

	// Whether ALPN is turned on. Value:
	AlpnEnabled *bool `json:"alpnEnabled,omitempty" tf:"alpn_enabled,omitempty"`

	// ALPN policy. Value:
	AlpnPolicy *string `json:"alpnPolicy,omitempty" tf:"alpn_policy,omitempty"`

	// CA certificate list information. Currently, only one CA certificate can be added.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	CACertificateIds []*string `json:"caCertificateIds,omitempty" tf:"ca_certificate_ids,omitempty"`

	// Whether to start two-way authentication. Value:
	CAEnabled *bool `json:"caEnabled,omitempty" tf:"ca_enabled,omitempty"`

	// Server certificate list information. Currently, only one server certificate can be added.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	CertificateIds []*string `json:"certificateIds,omitempty" tf:"certificate_ids,omitempty"`

	// The new connection speed limit for a network-based load balancing instance per second. Valid values: 0 ~ 1000000. 0 indicates unlimited speed.
	Cps *float64 `json:"cps,omitempty" tf:"cps,omitempty"`

	// Full port listening end port. Valid values: 0 ~ **65535 * *. The value of the end port is less than the start port.
	EndPort *float64 `json:"endPort,omitempty" tf:"end_port,omitempty"`

	// Connection idle timeout time. Unit: seconds. Valid values: 1 ~ 900.
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// Custom listener name.The length is limited to 2 to 256 characters, supports Chinese and English letters, and can include numbers, commas (,), half-width periods (.), half-width semicolons (;), forward slashes (/), at(@), underscores (_), and dashes (-).
	ListenerDescription *string `json:"listenerDescription,omitempty" tf:"listener_description,omitempty"`

	// Listening port. Valid values: 0 ~ **65535 * *. 0: indicates that full port listening is used. When set to 0, you must configure StartPort and EndPort.
	ListenerPort *float64 `json:"listenerPort,omitempty" tf:"listener_port,omitempty"`

	// The listening protocol. Valid values: TCP, UDP, or TCPSSL.
	ListenerProtocol *string `json:"listenerProtocol,omitempty" tf:"listener_protocol,omitempty"`

	// The ID of the network-based server load balancer instance.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// The maximum segment size of the TCP message. Unit: Bytes. Valid values: 0 ~ 1500. 0 indicates that the MSS value of the TCP message is not modified.
	// -> NOTE:  only TCP and TCPSSL listeners support this field value.
	Mss *float64 `json:"mss,omitempty" tf:"mss,omitempty"`

	// Whether to enable the Proxy Protocol to carry the source address of the client to the backend server. Value:
	ProxyProtocolEnabled *bool `json:"proxyProtocolEnabled,omitempty" tf:"proxy_protocol_enabled,omitempty"`

	// Whether to turn on the second-level monitoring function. Value:
	SecSensorEnabled *bool `json:"secSensorEnabled,omitempty" tf:"sec_sensor_enabled,omitempty"`

	// Security policy ID. Support system security policies and custom security policies. Valid values: tls_cipher_policy_1_0, tls_cipher_policy_1_1, tls_cipher_policy_1_2, tls_cipher_policy_1_2_strict, or tls_cipher_policy_1_2_strict_with_1_3.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`

	// The ID of the server group.
	ServerGroupID *string `json:"serverGroupId,omitempty" tf:"server_group_id,omitempty"`

	// Full Port listens to the starting port. Valid values: 0 ~ 65535.
	StartPort *float64 `json:"startPort,omitempty" tf:"start_port,omitempty"`

	// The status of the resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tag of the resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ListenerObservation struct {

	// Whether ALPN is turned on. Value:
	AlpnEnabled *bool `json:"alpnEnabled,omitempty" tf:"alpn_enabled,omitempty"`

	// ALPN policy. Value:
	AlpnPolicy *string `json:"alpnPolicy,omitempty" tf:"alpn_policy,omitempty"`

	// CA certificate list information. Currently, only one CA certificate can be added.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	CACertificateIds []*string `json:"caCertificateIds,omitempty" tf:"ca_certificate_ids,omitempty"`

	// Whether to start two-way authentication. Value:
	CAEnabled *bool `json:"caEnabled,omitempty" tf:"ca_enabled,omitempty"`

	// Server certificate list information. Currently, only one server certificate can be added.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	CertificateIds []*string `json:"certificateIds,omitempty" tf:"certificate_ids,omitempty"`

	// The new connection speed limit for a network-based load balancing instance per second. Valid values: 0 ~ 1000000. 0 indicates unlimited speed.
	Cps *float64 `json:"cps,omitempty" tf:"cps,omitempty"`

	// Full port listening end port. Valid values: 0 ~ **65535 * *. The value of the end port is less than the start port.
	EndPort *float64 `json:"endPort,omitempty" tf:"end_port,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Connection idle timeout time. Unit: seconds. Valid values: 1 ~ 900.
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// Custom listener name.The length is limited to 2 to 256 characters, supports Chinese and English letters, and can include numbers, commas (,), half-width periods (.), half-width semicolons (;), forward slashes (/), at(@), underscores (_), and dashes (-).
	ListenerDescription *string `json:"listenerDescription,omitempty" tf:"listener_description,omitempty"`

	// Listening port. Valid values: 0 ~ **65535 * *. 0: indicates that full port listening is used. When set to 0, you must configure StartPort and EndPort.
	ListenerPort *float64 `json:"listenerPort,omitempty" tf:"listener_port,omitempty"`

	// The listening protocol. Valid values: TCP, UDP, or TCPSSL.
	ListenerProtocol *string `json:"listenerProtocol,omitempty" tf:"listener_protocol,omitempty"`

	// The ID of the network-based server load balancer instance.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// The maximum segment size of the TCP message. Unit: Bytes. Valid values: 0 ~ 1500. 0 indicates that the MSS value of the TCP message is not modified.
	// -> NOTE:  only TCP and TCPSSL listeners support this field value.
	Mss *float64 `json:"mss,omitempty" tf:"mss,omitempty"`

	// Whether to enable the Proxy Protocol to carry the source address of the client to the backend server. Value:
	ProxyProtocolEnabled *bool `json:"proxyProtocolEnabled,omitempty" tf:"proxy_protocol_enabled,omitempty"`

	// Whether to turn on the second-level monitoring function. Value:
	SecSensorEnabled *bool `json:"secSensorEnabled,omitempty" tf:"sec_sensor_enabled,omitempty"`

	// Security policy ID. Support system security policies and custom security policies. Valid values: tls_cipher_policy_1_0, tls_cipher_policy_1_1, tls_cipher_policy_1_2, tls_cipher_policy_1_2_strict, or tls_cipher_policy_1_2_strict_with_1_3.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`

	// The ID of the server group.
	ServerGroupID *string `json:"serverGroupId,omitempty" tf:"server_group_id,omitempty"`

	// Full Port listens to the starting port. Valid values: 0 ~ 65535.
	StartPort *float64 `json:"startPort,omitempty" tf:"start_port,omitempty"`

	// The status of the resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tag of the resource.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ListenerParameters struct {

	// Whether ALPN is turned on. Value:
	// +kubebuilder:validation:Optional
	AlpnEnabled *bool `json:"alpnEnabled,omitempty" tf:"alpn_enabled,omitempty"`

	// ALPN policy. Value:
	// +kubebuilder:validation:Optional
	AlpnPolicy *string `json:"alpnPolicy,omitempty" tf:"alpn_policy,omitempty"`

	// CA certificate list information. Currently, only one CA certificate can be added.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	// +kubebuilder:validation:Optional
	CACertificateIds []*string `json:"caCertificateIds,omitempty" tf:"ca_certificate_ids,omitempty"`

	// Whether to start two-way authentication. Value:
	// +kubebuilder:validation:Optional
	CAEnabled *bool `json:"caEnabled,omitempty" tf:"ca_enabled,omitempty"`

	// Server certificate list information. Currently, only one server certificate can be added.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	// +kubebuilder:validation:Optional
	CertificateIds []*string `json:"certificateIds,omitempty" tf:"certificate_ids,omitempty"`

	// The new connection speed limit for a network-based load balancing instance per second. Valid values: 0 ~ 1000000. 0 indicates unlimited speed.
	// +kubebuilder:validation:Optional
	Cps *float64 `json:"cps,omitempty" tf:"cps,omitempty"`

	// Full port listening end port. Valid values: 0 ~ **65535 * *. The value of the end port is less than the start port.
	// +kubebuilder:validation:Optional
	EndPort *float64 `json:"endPort,omitempty" tf:"end_port,omitempty"`

	// Connection idle timeout time. Unit: seconds. Valid values: 1 ~ 900.
	// +kubebuilder:validation:Optional
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// Custom listener name.The length is limited to 2 to 256 characters, supports Chinese and English letters, and can include numbers, commas (,), half-width periods (.), half-width semicolons (;), forward slashes (/), at(@), underscores (_), and dashes (-).
	// +kubebuilder:validation:Optional
	ListenerDescription *string `json:"listenerDescription,omitempty" tf:"listener_description,omitempty"`

	// Listening port. Valid values: 0 ~ **65535 * *. 0: indicates that full port listening is used. When set to 0, you must configure StartPort and EndPort.
	// +kubebuilder:validation:Optional
	ListenerPort *float64 `json:"listenerPort,omitempty" tf:"listener_port,omitempty"`

	// The listening protocol. Valid values: TCP, UDP, or TCPSSL.
	// +kubebuilder:validation:Optional
	ListenerProtocol *string `json:"listenerProtocol,omitempty" tf:"listener_protocol,omitempty"`

	// The ID of the network-based server load balancer instance.
	// +kubebuilder:validation:Optional
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// The maximum segment size of the TCP message. Unit: Bytes. Valid values: 0 ~ 1500. 0 indicates that the MSS value of the TCP message is not modified.
	// -> NOTE:  only TCP and TCPSSL listeners support this field value.
	// +kubebuilder:validation:Optional
	Mss *float64 `json:"mss,omitempty" tf:"mss,omitempty"`

	// Whether to enable the Proxy Protocol to carry the source address of the client to the backend server. Value:
	// +kubebuilder:validation:Optional
	ProxyProtocolEnabled *bool `json:"proxyProtocolEnabled,omitempty" tf:"proxy_protocol_enabled,omitempty"`

	// Whether to turn on the second-level monitoring function. Value:
	// +kubebuilder:validation:Optional
	SecSensorEnabled *bool `json:"secSensorEnabled,omitempty" tf:"sec_sensor_enabled,omitempty"`

	// Security policy ID. Support system security policies and custom security policies. Valid values: tls_cipher_policy_1_0, tls_cipher_policy_1_1, tls_cipher_policy_1_2, tls_cipher_policy_1_2_strict, or tls_cipher_policy_1_2_strict_with_1_3.
	// -> NOTE:  This parameter only takes effect for TCPSSL listeners.
	// +kubebuilder:validation:Optional
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`

	// The ID of the server group.
	// +kubebuilder:validation:Optional
	ServerGroupID *string `json:"serverGroupId,omitempty" tf:"server_group_id,omitempty"`

	// Full Port listens to the starting port. Valid values: 0 ~ 65535.
	// +kubebuilder:validation:Optional
	StartPort *float64 `json:"startPort,omitempty" tf:"start_port,omitempty"`

	// The status of the resource.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tag of the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// ListenerSpec defines the desired state of Listener
type ListenerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ListenerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ListenerInitParameters `json:"initProvider,omitempty"`
}

// ListenerStatus defines the observed state of Listener.
type ListenerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ListenerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Listener is the Schema for the Listeners API. Provides a Alicloud NLB Listener resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Listener struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.listenerPort) || (has(self.initProvider) && has(self.initProvider.listenerPort))",message="spec.forProvider.listenerPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.listenerProtocol) || (has(self.initProvider) && has(self.initProvider.listenerProtocol))",message="spec.forProvider.listenerProtocol is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loadBalancerId) || (has(self.initProvider) && has(self.initProvider.loadBalancerId))",message="spec.forProvider.loadBalancerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverGroupId) || (has(self.initProvider) && has(self.initProvider.serverGroupId))",message="spec.forProvider.serverGroupId is a required parameter"
	Spec   ListenerSpec   `json:"spec"`
	Status ListenerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ListenerList contains a list of Listeners
type ListenerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Listener `json:"items"`
}

// Repository type metadata.
var (
	Listener_Kind             = "Listener"
	Listener_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Listener_Kind}.String()
	Listener_KindAPIVersion   = Listener_Kind + "." + CRDGroupVersion.String()
	Listener_GroupVersionKind = CRDGroupVersion.WithKind(Listener_Kind)
)

func init() {
	SchemeBuilder.Register(&Listener{}, &ListenerList{})
}
