// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright (c) 2024-2025, Alibaba Cloud and its affiliates;

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type HealthCheckInitParameters struct {

	// The health check method. Valid values: GET or HEAD.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	HTTPCheckMethod *string `json:"httpCheckMethod,omitempty" tf:"http_check_method,omitempty"`

	// The port of the backend server for health checks. Valid values: 0 ~ 65535. 0 indicates that the port of the backend server is used for health check.
	HealthCheckConnectPort *float64 `json:"healthCheckConnectPort,omitempty" tf:"health_check_connect_port,omitempty"`

	// Maximum timeout for health check responses. Unit: seconds. Valid values: 1 ~ 300.
	HealthCheckConnectTimeout *float64 `json:"healthCheckConnectTimeout,omitempty" tf:"health_check_connect_timeout,omitempty"`

	// The domain name used for health check. Valid values:
	HealthCheckDomain *string `json:"healthCheckDomain,omitempty" tf:"health_check_domain,omitempty"`

	// Whether to enable health check. Valid values:
	HealthCheckEnabled *bool `json:"healthCheckEnabled,omitempty" tf:"health_check_enabled,omitempty"`

	// Health status return code. Multiple status codes are separated by commas (,). Valid values: http_2xx, http_3xx, http_4xx, and http_5xx.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	HealthCheckHTTPCode []*string `json:"healthCheckHttpCode,omitempty" tf:"health_check_http_code,omitempty"`

	// Time interval of health examination. Unit: seconds.Valid values: 5 ~ 50.
	HealthCheckInterval *float64 `json:"healthCheckInterval,omitempty" tf:"health_check_interval,omitempty"`

	// Health check protocol. Valid values: TCP or HTTP.
	HealthCheckType *string `json:"healthCheckType,omitempty" tf:"health_check_type,omitempty"`

	// Health check path.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	HealthCheckURL *string `json:"healthCheckUrl,omitempty" tf:"health_check_url,omitempty"`

	// After the health check is successful, the health check status of the backend server is determined from failed to **successful * *.Valid values: 2 to **10 * *.
	HealthyThreshold *float64 `json:"healthyThreshold,omitempty" tf:"healthy_threshold,omitempty"`

	// After the health check fails for many times in a row, the health check status of the backend server is determined from Success to Failure. Valid values: 2 to 10.
	UnhealthyThreshold *float64 `json:"unhealthyThreshold,omitempty" tf:"unhealthy_threshold,omitempty"`
}

type HealthCheckObservation struct {

	// The health check method. Valid values: GET or HEAD.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	HTTPCheckMethod *string `json:"httpCheckMethod,omitempty" tf:"http_check_method,omitempty"`

	// The port of the backend server for health checks. Valid values: 0 ~ 65535. 0 indicates that the port of the backend server is used for health check.
	HealthCheckConnectPort *float64 `json:"healthCheckConnectPort,omitempty" tf:"health_check_connect_port,omitempty"`

	// Maximum timeout for health check responses. Unit: seconds. Valid values: 1 ~ 300.
	HealthCheckConnectTimeout *float64 `json:"healthCheckConnectTimeout,omitempty" tf:"health_check_connect_timeout,omitempty"`

	// The domain name used for health check. Valid values:
	HealthCheckDomain *string `json:"healthCheckDomain,omitempty" tf:"health_check_domain,omitempty"`

	// Whether to enable health check. Valid values:
	HealthCheckEnabled *bool `json:"healthCheckEnabled,omitempty" tf:"health_check_enabled,omitempty"`

	// Health status return code. Multiple status codes are separated by commas (,). Valid values: http_2xx, http_3xx, http_4xx, and http_5xx.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	HealthCheckHTTPCode []*string `json:"healthCheckHttpCode,omitempty" tf:"health_check_http_code,omitempty"`

	// Time interval of health examination. Unit: seconds.Valid values: 5 ~ 50.
	HealthCheckInterval *float64 `json:"healthCheckInterval,omitempty" tf:"health_check_interval,omitempty"`

	// Health check protocol. Valid values: TCP or HTTP.
	HealthCheckType *string `json:"healthCheckType,omitempty" tf:"health_check_type,omitempty"`

	// Health check path.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	HealthCheckURL *string `json:"healthCheckUrl,omitempty" tf:"health_check_url,omitempty"`

	// After the health check is successful, the health check status of the backend server is determined from failed to **successful * *.Valid values: 2 to **10 * *.
	HealthyThreshold *float64 `json:"healthyThreshold,omitempty" tf:"healthy_threshold,omitempty"`

	// After the health check fails for many times in a row, the health check status of the backend server is determined from Success to Failure. Valid values: 2 to 10.
	UnhealthyThreshold *float64 `json:"unhealthyThreshold,omitempty" tf:"unhealthy_threshold,omitempty"`
}

type HealthCheckParameters struct {

	// The health check method. Valid values: GET or HEAD.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	// +kubebuilder:validation:Optional
	HTTPCheckMethod *string `json:"httpCheckMethod,omitempty" tf:"http_check_method,omitempty"`

	// The port of the backend server for health checks. Valid values: 0 ~ 65535. 0 indicates that the port of the backend server is used for health check.
	// +kubebuilder:validation:Optional
	HealthCheckConnectPort *float64 `json:"healthCheckConnectPort,omitempty" tf:"health_check_connect_port,omitempty"`

	// Maximum timeout for health check responses. Unit: seconds. Valid values: 1 ~ 300.
	// +kubebuilder:validation:Optional
	HealthCheckConnectTimeout *float64 `json:"healthCheckConnectTimeout,omitempty" tf:"health_check_connect_timeout,omitempty"`

	// The domain name used for health check. Valid values:
	// +kubebuilder:validation:Optional
	HealthCheckDomain *string `json:"healthCheckDomain,omitempty" tf:"health_check_domain,omitempty"`

	// Whether to enable health check. Valid values:
	// +kubebuilder:validation:Optional
	HealthCheckEnabled *bool `json:"healthCheckEnabled,omitempty" tf:"health_check_enabled,omitempty"`

	// Health status return code. Multiple status codes are separated by commas (,). Valid values: http_2xx, http_3xx, http_4xx, and http_5xx.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	// +kubebuilder:validation:Optional
	HealthCheckHTTPCode []*string `json:"healthCheckHttpCode,omitempty" tf:"health_check_http_code,omitempty"`

	// Time interval of health examination. Unit: seconds.Valid values: 5 ~ 50.
	// +kubebuilder:validation:Optional
	HealthCheckInterval *float64 `json:"healthCheckInterval,omitempty" tf:"health_check_interval,omitempty"`

	// Health check protocol. Valid values: TCP or HTTP.
	// +kubebuilder:validation:Optional
	HealthCheckType *string `json:"healthCheckType,omitempty" tf:"health_check_type,omitempty"`

	// Health check path.
	// -> NOTE:  This parameter takes effect only when HealthCheckType is HTTP.
	// +kubebuilder:validation:Optional
	HealthCheckURL *string `json:"healthCheckUrl,omitempty" tf:"health_check_url,omitempty"`

	// After the health check is successful, the health check status of the backend server is determined from failed to **successful * *.Valid values: 2 to **10 * *.
	// +kubebuilder:validation:Optional
	HealthyThreshold *float64 `json:"healthyThreshold,omitempty" tf:"healthy_threshold,omitempty"`

	// After the health check fails for many times in a row, the health check status of the backend server is determined from Success to Failure. Valid values: 2 to 10.
	// +kubebuilder:validation:Optional
	UnhealthyThreshold *float64 `json:"unhealthyThreshold,omitempty" tf:"unhealthy_threshold,omitempty"`
}

type ServerGroupInitParameters struct {

	// Protocol version. Value:
	AddressIPVersion *string `json:"addressIpVersion,omitempty" tf:"address_ip_version,omitempty"`

	// Full port forwarding.
	AnyPortEnabled *bool `json:"anyPortEnabled,omitempty" tf:"any_port_enabled,omitempty"`

	// (Deprecated since v1.214.0). Field 'connection_drain' has been deprecated from provider version 1.214.0. New field 'connection_drain_enabled' instead.
	ConnectionDrain *bool `json:"connectionDrain,omitempty" tf:"connection_drain,omitempty"`

	// Whether to open the connection gracefully interrupted. Value:
	ConnectionDrainEnabled *bool `json:"connectionDrainEnabled,omitempty" tf:"connection_drain_enabled,omitempty"`

	// Set the connection elegant interrupt timeout. Unit: seconds. Valid values: 10 ~ 900.
	ConnectionDrainTimeout *float64 `json:"connectionDrainTimeout,omitempty" tf:"connection_drain_timeout,omitempty"`

	// Health check configuration information. See health_check below.
	HealthCheck []HealthCheckInitParameters `json:"healthCheck,omitempty" tf:"health_check,omitempty"`

	// Whether to enable the client address retention function. Value:
	PreserveClientIPEnabled *bool `json:"preserveClientIpEnabled,omitempty" tf:"preserve_client_ip_enabled,omitempty"`

	// The backend Forwarding Protocol. Valid values: TCP, UDP, or TCPSSL.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The ID of the resource group to which the server group belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Scheduling algorithm. Value:
	Scheduler *string `json:"scheduler,omitempty" tf:"scheduler,omitempty"`

	// The name of the server group.
	ServerGroupName *string `json:"serverGroupName,omitempty" tf:"server_group_name,omitempty"`

	// Server group type. Value:
	ServerGroupType *string `json:"serverGroupType,omitempty" tf:"server_group_type,omitempty"`

	// Label.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the VPC to which the server group belongs.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type ServerGroupObservation struct {

	// Protocol version. Value:
	AddressIPVersion *string `json:"addressIpVersion,omitempty" tf:"address_ip_version,omitempty"`

	// Full port forwarding.
	AnyPortEnabled *bool `json:"anyPortEnabled,omitempty" tf:"any_port_enabled,omitempty"`

	// (Deprecated since v1.214.0). Field 'connection_drain' has been deprecated from provider version 1.214.0. New field 'connection_drain_enabled' instead.
	ConnectionDrain *bool `json:"connectionDrain,omitempty" tf:"connection_drain,omitempty"`

	// Whether to open the connection gracefully interrupted. Value:
	ConnectionDrainEnabled *bool `json:"connectionDrainEnabled,omitempty" tf:"connection_drain_enabled,omitempty"`

	// Set the connection elegant interrupt timeout. Unit: seconds. Valid values: 10 ~ 900.
	ConnectionDrainTimeout *float64 `json:"connectionDrainTimeout,omitempty" tf:"connection_drain_timeout,omitempty"`

	// Health check configuration information. See health_check below.
	HealthCheck []HealthCheckObservation `json:"healthCheck,omitempty" tf:"health_check,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether to enable the client address retention function. Value:
	PreserveClientIPEnabled *bool `json:"preserveClientIpEnabled,omitempty" tf:"preserve_client_ip_enabled,omitempty"`

	// The backend Forwarding Protocol. Valid values: TCP, UDP, or TCPSSL.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The ID of the resource group to which the server group belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Scheduling algorithm. Value:
	Scheduler *string `json:"scheduler,omitempty" tf:"scheduler,omitempty"`

	// The name of the server group.
	ServerGroupName *string `json:"serverGroupName,omitempty" tf:"server_group_name,omitempty"`

	// Server group type. Value:
	ServerGroupType *string `json:"serverGroupType,omitempty" tf:"server_group_type,omitempty"`

	// Server group status. Value:
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Label.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the VPC to which the server group belongs.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type ServerGroupParameters struct {

	// Protocol version. Value:
	// +kubebuilder:validation:Optional
	AddressIPVersion *string `json:"addressIpVersion,omitempty" tf:"address_ip_version,omitempty"`

	// Full port forwarding.
	// +kubebuilder:validation:Optional
	AnyPortEnabled *bool `json:"anyPortEnabled,omitempty" tf:"any_port_enabled,omitempty"`

	// (Deprecated since v1.214.0). Field 'connection_drain' has been deprecated from provider version 1.214.0. New field 'connection_drain_enabled' instead.
	// +kubebuilder:validation:Optional
	ConnectionDrain *bool `json:"connectionDrain,omitempty" tf:"connection_drain,omitempty"`

	// Whether to open the connection gracefully interrupted. Value:
	// +kubebuilder:validation:Optional
	ConnectionDrainEnabled *bool `json:"connectionDrainEnabled,omitempty" tf:"connection_drain_enabled,omitempty"`

	// Set the connection elegant interrupt timeout. Unit: seconds. Valid values: 10 ~ 900.
	// +kubebuilder:validation:Optional
	ConnectionDrainTimeout *float64 `json:"connectionDrainTimeout,omitempty" tf:"connection_drain_timeout,omitempty"`

	// Health check configuration information. See health_check below.
	// +kubebuilder:validation:Optional
	HealthCheck []HealthCheckParameters `json:"healthCheck,omitempty" tf:"health_check,omitempty"`

	// Whether to enable the client address retention function. Value:
	// +kubebuilder:validation:Optional
	PreserveClientIPEnabled *bool `json:"preserveClientIpEnabled,omitempty" tf:"preserve_client_ip_enabled,omitempty"`

	// The backend Forwarding Protocol. Valid values: TCP, UDP, or TCPSSL.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The ID of the resource group to which the server group belongs.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Scheduling algorithm. Value:
	// +kubebuilder:validation:Optional
	Scheduler *string `json:"scheduler,omitempty" tf:"scheduler,omitempty"`

	// The name of the server group.
	// +kubebuilder:validation:Optional
	ServerGroupName *string `json:"serverGroupName,omitempty" tf:"server_group_name,omitempty"`

	// Server group type. Value:
	// +kubebuilder:validation:Optional
	ServerGroupType *string `json:"serverGroupType,omitempty" tf:"server_group_type,omitempty"`

	// Label.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The ID of the VPC to which the server group belongs.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

// ServerGroupSpec defines the desired state of ServerGroup
type ServerGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerGroupInitParameters `json:"initProvider,omitempty"`
}

// ServerGroupStatus defines the observed state of ServerGroup.
type ServerGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServerGroup is the Schema for the ServerGroups API. Provides a Alicloud NLB Server Group resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ServerGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverGroupName) || (has(self.initProvider) && has(self.initProvider.serverGroupName))",message="spec.forProvider.serverGroupName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpcId) || (has(self.initProvider) && has(self.initProvider.vpcId))",message="spec.forProvider.vpcId is a required parameter"
	Spec   ServerGroupSpec   `json:"spec"`
	Status ServerGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerGroupList contains a list of ServerGroups
type ServerGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerGroup `json:"items"`
}

// Repository type metadata.
var (
	ServerGroup_Kind             = "ServerGroup"
	ServerGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerGroup_Kind}.String()
	ServerGroup_KindAPIVersion   = ServerGroup_Kind + "." + CRDGroupVersion.String()
	ServerGroup_GroupVersionKind = CRDGroupVersion.WithKind(ServerGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerGroup{}, &ServerGroupList{})
}
